import astropy.units as u
import pytest
from benchmark import Benchmark, benchmark


@benchmark(
    {
        "log.initial.system.Age": {"value": 0.000000, "unit": u.sec},
        "log.initial.system.Time": {"value": 0.000000, "unit": u.sec},
        "log.initial.system.TotAngMom": {
            "value": 2.238488e42,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.system.TotEnergy": {"value": -2.973009e39, "unit": u.Joule},
        "log.initial.system.PotEnergy": {"value": -3.053797e39, "unit": u.Joule},
        "log.initial.system.KinEnergy": {"value": 8.083873e37, "unit": u.Joule},
        "log.initial.system.DeltaTime": {"value": 0.000000, "unit": u.sec},
        "log.initial.star.Mass": {"value": 2.346331e29, "unit": u.kg},
        "log.initial.star.Radius": {"value": 7.219282e08, "unit": u.m},
        "log.initial.star.RadGyra": {"value": 0.500000},
        "log.initial.star.RotAngMom": {
            "value": 2.223225e42,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.star.RotVel": {"value": 5.250010e04, "unit": u.m / u.sec},
        "log.initial.star.BodyType": {"value": 0.000000},
        "log.initial.star.RotRate": {"value": 7.272205e-05, "unit": 1 / u.sec},
        "log.initial.star.RotPer": {"value": 8.640000e04, "unit": u.sec},
        "log.initial.star.Density": {"value": 148.873947, "unit": u.kg / u.m**3},
        "log.initial.star.HZLimitDryRunaway": {"value": 3.167291e10, "unit": u.m},
        "log.initial.star.HZLimRecVenus": {"value": 2.860627e10, "unit": u.m},
        "log.initial.star.HZLimRunaway": {"value": 3.759816e10, "unit": u.m},
        "log.initial.star.HZLimMoistGreenhouse": {"value": 3.785088e10, "unit": u.m},
        "log.initial.star.HZLimMaxGreenhouse": {"value": 7.322892e10, "unit": u.m},
        "log.initial.star.HZLimEarlyMars": {"value": 7.986486e10, "unit": u.m},
        "log.initial.star.Instellation": {
            "value": -1.000000,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.star.CriticalSemiMajorAxis": {"value": -1.000000, "unit": u.m},
        "log.initial.star.LXUVTot": {"value": 5.441075e-05, "unit": u.LSUN},
        "log.initial.star.LostEnergy": {"value": 5.562685e-309, "unit": u.Joule},
        "log.initial.star.LostAngMom": {
            "value": 5.562685e-309,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.star.Luminosity": {"value": 0.054411, "unit": u.LSUN},
        "log.initial.star.LXUVStellar": {"value": 2.092637e22, "unit": u.W},
        "log.initial.star.Temperature": {"value": 2739.815007, "unit": u.K},
        "log.initial.star.LXUVFrac": {"value": 0.001000},
        "log.initial.star.RossbyNumber": {"value": 0.012946},
        "log.initial.star.DRotPerDtStellar": {"value": 1.613569e-09},
        "log.initial.ProxCenELim.Mass": {"value": 7.584676e24, "unit": u.kg},
        "log.initial.ProxCenELim.Radius": {"value": 1.379805, "unit": u.Rearth},
        "log.initial.ProxCenELim.RadGyra": {"value": 0.500000},
        "log.initial.ProxCenELim.BodyType": {"value": 0.000000},
        "log.initial.ProxCenELim.Density": {
            "value": 2656.570214,
            "unit": u.kg / u.m**3,
        },
        "log.initial.ProxCenELim.HZLimitDryRunaway": {
            "value": 3.183247e10,
            "unit": u.m,
        },
        "log.initial.ProxCenELim.HZLimRecVenus": {"value": 2.860627e10, "unit": u.m},
        "log.initial.ProxCenELim.HZLimRunaway": {"value": 0.251328, "unit": u.au},
        "log.initial.ProxCenELim.HZLimMoistGreenhouse": {
            "value": 3.785088e10,
            "unit": u.m,
        },
        "log.initial.ProxCenELim.HZLimMaxGreenhouse": {"value": 0.489505, "unit": u.au},
        "log.initial.ProxCenELim.HZLimEarlyMars": {"value": 7.986486e10, "unit": u.m},
        "log.initial.ProxCenELim.Instellation": {
            "value": 3.179305e04,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.ProxCenELim.MeanMotion": {
            "value": 6.403289e-06,
            "unit": 1 / u.sec,
        },
        "log.initial.ProxCenELim.OrbPeriod": {"value": 9.812434e05, "unit": u.sec},
        "log.initial.ProxCenELim.SemiMajorAxis": {"value": 7.255497e09, "unit": u.m},
        "log.initial.ProxCenELim.LXUVTot": {
            "value": -1.000000,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.ProxCenELim.SurfWaterMass": {"value": 1.500000, "unit": u.TO},
        "log.initial.ProxCenELim.EnvelopeMass": {"value": 0.001000, "unit": u.Mearth},
        "log.initial.ProxCenELim.OxygenMass": {"value": 0.000000, "unit": u.bar},
        "log.initial.ProxCenELim.RGLimit": {"value": 3.618320e10, "unit": u.m},
        "log.initial.ProxCenELim.XO": {"value": 0.333333},
        "log.initial.ProxCenELim.EtaO": {"value": 0.000000},
        "log.initial.ProxCenELim.PlanetRadius": {"value": 1.379805, "unit": u.Rearth},
        "log.initial.ProxCenELim.OxygenMantleMass": {"value": 0.000000, "unit": u.kg},
        "log.initial.ProxCenELim.RadXUV": {"value": -1.000000, "unit": u.m},
        "log.initial.ProxCenELim.RadSolid": {"value": -1.000000, "unit": u.m},
        "log.initial.ProxCenELim.PresXUV": {"value": 5.000000},
        "log.initial.ProxCenELim.ScaleHeight": {"value": -1.000000, "unit": u.m},
        "log.initial.ProxCenELim.ThermTemp": {"value": 400.000000, "unit": u.K},
        "log.initial.ProxCenELim.AtmGasConst": {"value": 4124.000000},
        "log.initial.ProxCenELim.PresSurf": {"value": -1.000000, "unit": u.Pa},
        "log.initial.ProxCenELim.DEnvMassDt": {
            "value": -2.198134e07,
            "unit": u.kg / u.sec,
        },
        "log.initial.ProxCenELim.FXUV": {"value": 31.793050, "unit": u.W / u.m**2},
        "log.initial.ProxCenELim.AtmXAbsEffH2O": {"value": 0.300000},
        "log.initial.ProxCenELim.RocheRadius": {"value": 1.602542e08, "unit": u.m},
        "log.initial.ProxCenELim.BondiRadius": {"value": 1.427762e08, "unit": u.m},
        "log.initial.ProxCenELim.HEscapeRegime": {"value": 3.000000},
        "log.initial.ProxCenELim.RRCriticalFlux": {
            "value": 27.771659,
            "unit": u.W / u.m**2,
        },
        "log.initial.ProxCenELim.KTide": {"value": 0.917709},
        "log.initial.ProxCenELim.RGDuration": {"value": 0.00000e00, "unit": u.yr},
        "log.initial.ProxCenRRLim.Mass": {"value": 7.584676e24, "unit": u.kg},
        "log.initial.ProxCenRRLim.Radius": {"value": 1.379805, "unit": u.Rearth},
        "log.initial.ProxCenRRLim.RadGyra": {"value": 0.500000},
        "log.initial.ProxCenRRLim.BodyType": {"value": 0.000000},
        "log.initial.ProxCenRRLim.Density": {
            "value": 2656.570214,
            "unit": u.kg / u.m**3,
        },
        "log.initial.ProxCenRRLim.HZLimitDryRunaway": {
            "value": 3.183247e10,
            "unit": u.m,
        },
        "log.initial.ProxCenRRLim.HZLimRecVenus": {"value": 2.860627e10, "unit": u.m},
        "log.initial.ProxCenRRLim.HZLimRunaway": {"value": 0.251328, "unit": u.au},
        "log.initial.ProxCenRRLim.HZLimMoistGreenhouse": {
            "value": 3.785088e10,
            "unit": u.m,
        },
        "log.initial.ProxCenRRLim.HZLimMaxGreenhouse": {
            "value": 0.489505,
            "unit": u.au,
        },
        "log.initial.ProxCenRRLim.HZLimEarlyMars": {"value": 7.986486e10, "unit": u.m},
        "log.initial.ProxCenRRLim.Instellation": {
            "value": 3.179305e04,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.ProxCenRRLim.MeanMotion": {
            "value": 6.403289e-06,
            "unit": 1 / u.sec,
        },
        "log.initial.ProxCenRRLim.OrbPeriod": {"value": 9.812434e05, "unit": u.sec},
        "log.initial.ProxCenRRLim.SemiMajorAxis": {"value": 7.255497e09, "unit": u.m},
        "log.initial.ProxCenRRLim.LXUVTot": {
            "value": -1.000000,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.ProxCenRRLim.SurfWaterMass": {"value": 1.500000, "unit": u.TO},
        "log.initial.ProxCenRRLim.EnvelopeMass": {"value": 0.001000, "unit": u.Mearth},
        "log.initial.ProxCenRRLim.OxygenMass": {"value": 0.000000, "unit": u.bar},
        "log.initial.ProxCenRRLim.RGLimit": {"value": 3.618320e10, "unit": u.m},
        "log.initial.ProxCenRRLim.XO": {"value": 0.333333},
        "log.initial.ProxCenRRLim.EtaO": {"value": 0.000000},
        "log.initial.ProxCenRRLim.PlanetRadius": {"value": 1.379805, "unit": u.Rearth},
        "log.initial.ProxCenRRLim.OxygenMantleMass": {"value": 0.000000, "unit": u.kg},
        "log.initial.ProxCenRRLim.RadXUV": {"value": -1.000000, "unit": u.m},
        "log.initial.ProxCenRRLim.RadSolid": {"value": -1.000000, "unit": u.m},
        "log.initial.ProxCenRRLim.PresXUV": {"value": 5.000000},
        "log.initial.ProxCenRRLim.ScaleHeight": {"value": -1.000000, "unit": u.m},
        "log.initial.ProxCenRRLim.ThermTemp": {"value": 400.000000, "unit": u.K},
        "log.initial.ProxCenRRLim.AtmGasConst": {"value": 4124.000000},
        "log.initial.ProxCenRRLim.PresSurf": {"value": -1.000000, "unit": u.Pa},
        "log.initial.ProxCenRRLim.DEnvMassDt": {
            "value": -2.054766e07,
            "unit": u.kg / u.sec,
        },
        "log.initial.ProxCenRRLim.FXUV": {"value": 31.793050, "unit": u.W / u.m**2},
        "log.initial.ProxCenRRLim.AtmXAbsEffH2O": {"value": 0.300000},
        "log.initial.ProxCenRRLim.RocheRadius": {"value": 1.602542e08, "unit": u.m},
        "log.initial.ProxCenRRLim.BondiRadius": {"value": 1.427762e08, "unit": u.m},
        "log.initial.ProxCenRRLim.HEscapeRegime": {"value": 6.000000},
        "log.initial.ProxCenRRLim.RRCriticalFlux": {
            "value": 27.771659,
            "unit": u.W / u.m**2,
        },
        "log.initial.ProxCenRRLim.KTide": {"value": 0.917709},
        "log.initial.ProxCenRRLim.RGDuration": {"value": 0.00000e00, "unit": u.yr},
        "log.initial.ProxCenAuto.Mass": {"value": 7.584676e24, "unit": u.kg},
        "log.initial.ProxCenAuto.Radius": {"value": 1.379805, "unit": u.Rearth},
        "log.initial.ProxCenAuto.RadGyra": {"value": 0.500000},
        "log.initial.ProxCenAuto.BodyType": {"value": 0.000000},
        "log.initial.ProxCenAuto.Density": {
            "value": 2656.570214,
            "unit": u.kg / u.m**3,
        },
        "log.initial.ProxCenAuto.HZLimitDryRunaway": {
            "value": 3.183247e10,
            "unit": u.m,
        },
        "log.initial.ProxCenAuto.HZLimRecVenus": {"value": 2.860627e10, "unit": u.m},
        "log.initial.ProxCenAuto.HZLimRunaway": {"value": 0.251328, "unit": u.au},
        "log.initial.ProxCenAuto.HZLimMoistGreenhouse": {
            "value": 3.785088e10,
            "unit": u.m,
        },
        "log.initial.ProxCenAuto.HZLimMaxGreenhouse": {"value": 0.489505, "unit": u.au},
        "log.initial.ProxCenAuto.HZLimEarlyMars": {"value": 7.986486e10, "unit": u.m},
        "log.initial.ProxCenAuto.Instellation": {
            "value": 3.179305e04,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.ProxCenAuto.MeanMotion": {
            "value": 6.403289e-06,
            "unit": 1 / u.sec,
        },
        "log.initial.ProxCenAuto.OrbPeriod": {"value": 9.812434e05, "unit": u.sec},
        "log.initial.ProxCenAuto.SemiMajorAxis": {"value": 7.255497e09, "unit": u.m},
        "log.initial.ProxCenAuto.LXUVTot": {
            "value": -1.000000,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.ProxCenAuto.SurfWaterMass": {"value": 1.500000, "unit": u.TO},
        "log.initial.ProxCenAuto.EnvelopeMass": {"value": 0.001000, "unit": u.Mearth},
        "log.initial.ProxCenAuto.OxygenMass": {"value": 0.000000, "unit": u.bar},
        "log.initial.ProxCenAuto.RGLimit": {"value": 3.618320e10, "unit": u.m},
        "log.initial.ProxCenAuto.XO": {"value": 0.333333},
        "log.initial.ProxCenAuto.EtaO": {"value": 0.000000},
        "log.initial.ProxCenAuto.PlanetRadius": {"value": 1.379805, "unit": u.Rearth},
        "log.initial.ProxCenAuto.OxygenMantleMass": {"value": 0.000000, "unit": u.kg},
        "log.initial.ProxCenAuto.RadXUV": {"value": -1.000000, "unit": u.m},
        "log.initial.ProxCenAuto.RadSolid": {"value": -1.000000, "unit": u.m},
        "log.initial.ProxCenAuto.PresXUV": {"value": 5.000000},
        "log.initial.ProxCenAuto.ScaleHeight": {"value": -1.000000, "unit": u.m},
        "log.initial.ProxCenAuto.ThermTemp": {"value": 400.000000, "unit": u.K},
        "log.initial.ProxCenAuto.AtmGasConst": {"value": 4124.000000},
        "log.initial.ProxCenAuto.PresSurf": {"value": -1.000000, "unit": u.Pa},
        "log.initial.ProxCenAuto.DEnvMassDt": {
            "value": -2.198134e07,
            "unit": u.kg / u.sec,
        },
        "log.initial.ProxCenAuto.FXUV": {"value": 31.793050, "unit": u.W / u.m**2},
        "log.initial.ProxCenAuto.AtmXAbsEffH2O": {"value": 0.300000},
        "log.initial.ProxCenAuto.RocheRadius": {"value": 1.602542e08, "unit": u.m},
        "log.initial.ProxCenAuto.BondiRadius": {"value": 1.427762e08, "unit": u.m},
        "log.initial.ProxCenAuto.HEscapeRegime": {"value": 3.000000},
        "log.initial.ProxCenAuto.RRCriticalFlux": {
            "value": 27.771659,
            "unit": u.W / u.m**2,
        },
        "log.initial.ProxCenAuto.KTide": {"value": 0.917709},
        "log.initial.ProxCenAuto.RGDuration": {"value": 0.00000e00, "unit": u.yr},
        "log.initial.LC17ELim.Mass": {"value": 7.584676e24, "unit": u.kg},
        "log.initial.LC17ELim.Radius": {"value": 6.290589, "unit": u.Rearth},
        "log.initial.LC17ELim.RadGyra": {"value": 0.500000},
        "log.initial.LC17ELim.BodyType": {"value": 0.000000},
        "log.initial.LC17ELim.Density": {"value": 28.035001, "unit": u.kg / u.m**3},
        "log.initial.LC17ELim.HZLimitDryRunaway": {"value": 3.183247e10, "unit": u.m},
        "log.initial.LC17ELim.HZLimRecVenus": {"value": 2.860627e10, "unit": u.m},
        "log.initial.LC17ELim.HZLimRunaway": {"value": 0.251328, "unit": u.au},
        "log.initial.LC17ELim.HZLimMoistGreenhouse": {
            "value": 3.785088e10,
            "unit": u.m,
        },
        "log.initial.LC17ELim.HZLimMaxGreenhouse": {"value": 0.489505, "unit": u.au},
        "log.initial.LC17ELim.HZLimEarlyMars": {"value": 7.986486e10, "unit": u.m},
        "log.initial.LC17ELim.Instellation": {
            "value": 3.179305e04,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.LC17ELim.MeanMotion": {"value": 6.403289e-06, "unit": 1 / u.sec},
        "log.initial.LC17ELim.OrbPeriod": {"value": 9.812434e05, "unit": u.sec},
        "log.initial.LC17ELim.SemiMajorAxis": {"value": 7.255497e09, "unit": u.m},
        "log.initial.LC17ELim.LXUVTot": {"value": -1.000000, "unit": u.kg / u.sec**3},
        "log.initial.LC17ELim.SurfWaterMass": {"value": 1.500000, "unit": u.TO},
        "log.initial.LC17ELim.EnvelopeMass": {"value": 0.001000, "unit": u.Mearth},
        "log.initial.LC17ELim.OxygenMass": {"value": 0.000000, "unit": u.bar},
        "log.initial.LC17ELim.RGLimit": {"value": 3.618320e10, "unit": u.m},
        "log.initial.LC17ELim.XO": {"value": 0.333333},
        "log.initial.LC17ELim.EtaO": {"value": 0.000000},
        "log.initial.LC17ELim.PlanetRadius": {"value": 6.290589, "unit": u.Rearth},
        "log.initial.LC17ELim.OxygenMantleMass": {"value": 0.000000, "unit": u.kg},
        "log.initial.LC17ELim.RadXUV": {"value": 4.012200e07, "unit": u.m},
        "log.initial.LC17ELim.RadSolid": {"value": 6.783190e06, "unit": u.m},
        "log.initial.LC17ELim.PresXUV": {"value": 5.000000},
        "log.initial.LC17ELim.ScaleHeight": {"value": 3.327601e05, "unit": u.m},
        "log.initial.LC17ELim.ThermTemp": {"value": 880.000000, "unit": u.K},
        "log.initial.LC17ELim.AtmGasConst": {"value": 4157.000000},
        "log.initial.LC17ELim.PresSurf": {"value": 1.135499e08, "unit": u.Pa},
        "log.initial.LC17ELim.DEnvMassDt": {
            "value": -3.023130e09,
            "unit": u.kg / u.sec,
        },
        "log.initial.LC17ELim.FXUV": {"value": 31.793050, "unit": u.W / u.m**2},
        "log.initial.LC17ELim.AtmXAbsEffH2O": {"value": 0.300000},
        "log.initial.LC17ELim.RocheRadius": {"value": 1.602542e08, "unit": u.m},
        "log.initial.LC17ELim.BondiRadius": {"value": 1.427762e08, "unit": u.m},
        "log.initial.LC17ELim.HEscapeRegime": {"value": 3.000000},
        "log.initial.LC17ELim.RRCriticalFlux": {
            "value": 0.139129,
            "unit": u.W / u.m**2,
        },
        "log.initial.LC17ELim.KTide": {"value": 0.632300},
        "log.initial.LC17ELim.RGDuration": {"value": 0.00000e00, "unit": u.yr},
        "log.initial.LC17RRLim.Mass": {"value": 7.584676e24, "unit": u.kg},
        "log.initial.LC17RRLim.Radius": {"value": 6.290589, "unit": u.Rearth},
        "log.initial.LC17RRLim.RadGyra": {"value": 0.500000},
        "log.initial.LC17RRLim.BodyType": {"value": 0.000000},
        "log.initial.LC17RRLim.Density": {"value": 28.035001, "unit": u.kg / u.m**3},
        "log.initial.LC17RRLim.HZLimitDryRunaway": {"value": 3.183247e10, "unit": u.m},
        "log.initial.LC17RRLim.HZLimRecVenus": {"value": 2.860627e10, "unit": u.m},
        "log.initial.LC17RRLim.HZLimRunaway": {"value": 0.251328, "unit": u.au},
        "log.initial.LC17RRLim.HZLimMoistGreenhouse": {
            "value": 3.785088e10,
            "unit": u.m,
        },
        "log.initial.LC17RRLim.HZLimMaxGreenhouse": {"value": 0.489505, "unit": u.au},
        "log.initial.LC17RRLim.HZLimEarlyMars": {"value": 7.986486e10, "unit": u.m},
        "log.initial.LC17RRLim.Instellation": {
            "value": 3.179305e04,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.LC17RRLim.MeanMotion": {"value": 6.403289e-06, "unit": 1 / u.sec},
        "log.initial.LC17RRLim.OrbPeriod": {"value": 9.812434e05, "unit": u.sec},
        "log.initial.LC17RRLim.SemiMajorAxis": {"value": 7.255497e09, "unit": u.m},
        "log.initial.LC17RRLim.LXUVTot": {
            "value": -1.000000,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.LC17RRLim.SurfWaterMass": {"value": 1.500000, "unit": u.TO},
        "log.initial.LC17RRLim.EnvelopeMass": {"value": 0.001000, "unit": u.Mearth},
        "log.initial.LC17RRLim.OxygenMass": {"value": 0.000000, "unit": u.bar},
        "log.initial.LC17RRLim.RGLimit": {"value": 3.618320e10, "unit": u.m},
        "log.initial.LC17RRLim.XO": {"value": 0.333333},
        "log.initial.LC17RRLim.EtaO": {"value": 0.000000},
        "log.initial.LC17RRLim.PlanetRadius": {"value": 6.290589, "unit": u.Rearth},
        "log.initial.LC17RRLim.OxygenMantleMass": {"value": 0.000000, "unit": u.kg},
        "log.initial.LC17RRLim.RadXUV": {"value": 4.012200e07, "unit": u.m},
        "log.initial.LC17RRLim.RadSolid": {"value": 6.783190e06, "unit": u.m},
        "log.initial.LC17RRLim.PresXUV": {"value": 5.000000},
        "log.initial.LC17RRLim.ScaleHeight": {"value": 3.327601e05, "unit": u.m},
        "log.initial.LC17RRLim.ThermTemp": {"value": 880.000000, "unit": u.K},
        "log.initial.LC17RRLim.AtmGasConst": {"value": 4157.000000},
        "log.initial.LC17RRLim.PresSurf": {"value": 1.135499e08, "unit": u.Pa},
        "log.initial.LC17RRLim.DEnvMassDt": {
            "value": -2.000196e08,
            "unit": u.kg / u.sec,
        },
        "log.initial.LC17RRLim.FXUV": {"value": 31.793050, "unit": u.W / u.m**2},
        "log.initial.LC17RRLim.AtmXAbsEffH2O": {"value": 0.300000},
        "log.initial.LC17RRLim.RocheRadius": {"value": 1.602542e08, "unit": u.m},
        "log.initial.LC17RRLim.BondiRadius": {"value": 1.427762e08, "unit": u.m},
        "log.initial.LC17RRLim.HEscapeRegime": {"value": 6.000000},
        "log.initial.LC17RRLim.RRCriticalFlux": {
            "value": 0.139129,
            "unit": u.W / u.m**2,
        },
        "log.initial.LC17RRLim.KTide": {"value": 0.632300},
        "log.initial.LC17RRLim.RGDuration": {"value": 0.00000e00, "unit": u.yr},
        "log.initial.LC17Auto.Mass": {"value": 7.584676e24, "unit": u.kg},
        "log.initial.LC17Auto.Radius": {"value": 6.290589, "unit": u.Rearth},
        "log.initial.LC17Auto.RadGyra": {"value": 0.500000},
        "log.initial.LC17Auto.BodyType": {"value": 0.000000},
        "log.initial.LC17Auto.Density": {"value": 28.035001, "unit": u.kg / u.m**3},
        "log.initial.LC17Auto.HZLimitDryRunaway": {"value": 3.183247e10, "unit": u.m},
        "log.initial.LC17Auto.HZLimRecVenus": {"value": 2.860627e10, "unit": u.m},
        "log.initial.LC17Auto.HZLimRunaway": {"value": 0.251328, "unit": u.au},
        "log.initial.LC17Auto.HZLimMoistGreenhouse": {
            "value": 3.785088e10,
            "unit": u.m,
        },
        "log.initial.LC17Auto.HZLimMaxGreenhouse": {"value": 0.489505, "unit": u.au},
        "log.initial.LC17Auto.HZLimEarlyMars": {"value": 7.986486e10, "unit": u.m},
        "log.initial.LC17Auto.Instellation": {
            "value": 3.179305e04,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.LC17Auto.MeanMotion": {"value": 6.403289e-06, "unit": 1 / u.sec},
        "log.initial.LC17Auto.OrbPeriod": {"value": 9.812434e05, "unit": u.sec},
        "log.initial.LC17Auto.SemiMajorAxis": {"value": 7.255497e09, "unit": u.m},
        "log.initial.LC17Auto.LXUVTot": {"value": -1.000000, "unit": u.kg / u.sec**3},
        "log.initial.LC17Auto.SurfWaterMass": {"value": 1.500000, "unit": u.TO},
        "log.initial.LC17Auto.EnvelopeMass": {"value": 0.001000, "unit": u.Mearth},
        "log.initial.LC17Auto.OxygenMass": {"value": 0.000000, "unit": u.bar},
        "log.initial.LC17Auto.RGLimit": {"value": 3.618320e10, "unit": u.m},
        "log.initial.LC17Auto.XO": {"value": 0.333333},
        "log.initial.LC17Auto.EtaO": {"value": 0.000000},
        "log.initial.LC17Auto.PlanetRadius": {"value": 6.290589, "unit": u.Rearth},
        "log.initial.LC17Auto.OxygenMantleMass": {"value": 0.000000, "unit": u.kg},
        "log.initial.LC17Auto.RadXUV": {"value": 4.012200e07, "unit": u.m},
        "log.initial.LC17Auto.RadSolid": {"value": 6.783190e06, "unit": u.m},
        "log.initial.LC17Auto.PresXUV": {"value": 5.000000},
        "log.initial.LC17Auto.ScaleHeight": {"value": 3.327601e05, "unit": u.m},
        "log.initial.LC17Auto.ThermTemp": {"value": 880.000000, "unit": u.K},
        "log.initial.LC17Auto.AtmGasConst": {"value": 4157.000000},
        "log.initial.LC17Auto.PresSurf": {"value": 1.135499e08, "unit": u.Pa},
        "log.initial.LC17Auto.DEnvMassDt": {
            "value": -3.023130e09,
            "unit": u.kg / u.sec,
        },
        "log.initial.LC17Auto.FXUV": {"value": 31.793050, "unit": u.W / u.m**2},
        "log.initial.LC17Auto.AtmXAbsEffH2O": {"value": 0.300000},
        "log.initial.LC17Auto.RocheRadius": {"value": 1.602542e08, "unit": u.m},
        "log.initial.LC17Auto.BondiRadius": {"value": 1.427762e08, "unit": u.m},
        "log.initial.LC17Auto.HEscapeRegime": {"value": 3.000000},
        "log.initial.LC17Auto.RRCriticalFlux": {
            "value": 0.139129,
            "unit": u.W / u.m**2,
        },
        "log.initial.LC17Auto.KTide": {"value": 0.632300},
        "log.initial.LC17Auto.RGDuration": {"value": 0.00000e00, "unit": u.yr},
        "log.final.system.Age": {"value": 3.155760e14, "unit": u.sec, "rtol": 1e-4},
        "log.final.system.Time": {"value": 3.155760e14, "unit": u.sec, "rtol": 1e-4},
        "log.final.system.TotAngMom": {
            "value": 1.592522e42,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.system.TotEnergy": {
            "value": -6.771106e39,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.system.PotEnergy": {
            "value": -6.842608e39,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.system.KinEnergy": {
            "value": 4.957224e35,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.system.DeltaTime": {
            "value": 6.887448e09,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.star.Mass": {"value": 2.346331e29, "unit": u.kg, "rtol": 1e-4},
        "log.final.star.Radius": {"value": 3.221903e08, "unit": u.m, "rtol": 1e-4},
        "log.final.star.RadGyra": {"value": 0.500000, "rtol": 1e-4},
        "log.final.star.RotAngMom": {
            "value": 7.769828e40,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.star.RotVel": {
            "value": 4111.209813,
            "unit": u.m / u.sec,
            "rtol": 1e-4,
        },
        "log.final.star.BodyType": {"value": 0.000000, "rtol": 1e-4},
        "log.final.star.RotRate": {
            "value": 1.276019e-05,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.star.RotPer": {"value": 4.924053e05, "unit": u.sec, "rtol": 1e-4},
        "log.final.star.Density": {
            "value": 1674.800603,
            "unit": u.kg / u.m**3,
            "rtol": 1e-4,
        },
        "log.final.star.HZLimitDryRunaway": {
            "value": 1.546385e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.star.HZLimRecVenus": {
            "value": 1.393855e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.star.HZLimRunaway": {
            "value": 1.833264e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.star.HZLimMoistGreenhouse": {
            "value": 1.844302e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.star.HZLimMaxGreenhouse": {
            "value": 3.551046e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.star.HZLimEarlyMars": {
            "value": 3.872795e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.star.Instellation": {
            "value": -1.000000,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.star.CriticalSemiMajorAxis": {
            "value": -1.000000,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.star.LXUVTot": {"value": 1.297012e-05, "unit": u.LSUN, "rtol": 1e-4},
        "log.final.star.LostEnergy": {
            "value": 7.105751e37,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.star.LostAngMom": {
            "value": 1.499570e42,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.star.Luminosity": {"value": 0.012970, "unit": u.LSUN, "rtol": 1e-4},
        "log.final.star.LXUVStellar": {"value": 4.988309e21, "unit": u.W, "rtol": 1e-4},
        "log.final.star.Temperature": {"value": 2865.674217, "unit": u.K, "rtol": 1e-4},
        "log.final.star.LXUVFrac": {"value": 0.001000, "rtol": 1e-4},
        "log.final.star.RossbyNumber": {"value": 0.078695, "rtol": 1e-4},
        "log.final.star.DRotPerDtStellar": {"value": 6.246811e-10, "rtol": 1e-4},
        "log.final.ProxCenELim.Mass": {
            "value": 7.581607e24,
            "unit": u.kg,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.Radius": {
            "value": 1.336334,
            "unit": u.Rearth,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.RadGyra": {"value": 0.500000, "rtol": 1e-4},
        "log.final.ProxCenELim.BodyType": {"value": 0.000000, "rtol": 1e-4},
        "log.final.ProxCenELim.Density": {
            "value": 2923.166851,
            "unit": u.kg / u.m**3,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.HZLimitDryRunaway": {
            "value": 1.554176e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.HZLimRecVenus": {
            "value": 1.393855e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.HZLimRunaway": {
            "value": 0.122546,
            "unit": u.au,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.HZLimMoistGreenhouse": {
            "value": 1.844302e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.HZLimMaxGreenhouse": {
            "value": 0.237373,
            "unit": u.au,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.HZLimEarlyMars": {
            "value": 3.872795e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.Instellation": {
            "value": 7578.644938,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.MeanMotion": {
            "value": 6.403289e-06,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.OrbPeriod": {
            "value": 9.812434e05,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.SemiMajorAxis": {
            "value": 7.255497e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.LXUVTot": {
            "value": -1.000000,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.SurfWaterMass": {
            "value": 1.500000,
            "unit": u.TO,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.EnvelopeMass": {
            "value": 0.000486,
            "unit": u.Mearth,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.OxygenMass": {
            "value": 0.000000,
            "unit": u.bar,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.RGLimit": {
            "value": 1.763931e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.XO": {"value": 0.333333, "rtol": 1e-4},
        "log.final.ProxCenELim.EtaO": {"value": 0.000000, "rtol": 1e-4},
        "log.final.ProxCenELim.PlanetRadius": {
            "value": 1.336334,
            "unit": u.Rearth,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.OxygenMantleMass": {
            "value": 0.000000,
            "unit": u.kg,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.RadXUV": {"value": -1.000000, "unit": u.m, "rtol": 1e-4},
        "log.final.ProxCenELim.RadSolid": {
            "value": -1.000000,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.PresXUV": {"value": 5.000000, "rtol": 1e-4},
        "log.final.ProxCenELim.ScaleHeight": {
            "value": -1.000000,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.ThermTemp": {
            "value": 400.000000,
            "unit": u.K,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.AtmGasConst": {"value": 4124.000000, "rtol": 1e-4},
        "log.final.ProxCenELim.PresSurf": {
            "value": -1.000000,
            "unit": u.Pa,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.DEnvMassDt": {
            "value": -4.748597e06,
            "unit": u.kg / u.sec,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.FXUV": {
            "value": 7.578645,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.AtmXAbsEffH2O": {"value": 0.300000, "rtol": 1e-4},
        "log.final.ProxCenELim.RocheRadius": {
            "value": 1.602326e08,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.BondiRadius": {
            "value": 2.042514e08,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.HEscapeRegime": {"value": 3.000000, "rtol": 1e-4},
        "log.final.ProxCenELim.RRCriticalFlux": {
            "value": 30.718071,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.ProxCenELim.KTide": {"value": 0.920286, "rtol": 1e-4},
        "log.final.ProxCenELim.RGDuration": {
            "value": 0.00000e00,
            "unit": u.yr,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.Mass": {
            "value": 7.580496e24,
            "unit": u.kg,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.Radius": {
            "value": 1.339401,
            "unit": u.Rearth,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.RadGyra": {"value": 0.500000, "rtol": 1e-4},
        "log.final.ProxCenRRLim.BodyType": {"value": 0.000000, "rtol": 1e-4},
        "log.final.ProxCenRRLim.Density": {
            "value": 2902.708875,
            "unit": u.kg / u.m**3,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.HZLimitDryRunaway": {
            "value": 1.554176e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.HZLimRecVenus": {
            "value": 1.393855e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.HZLimRunaway": {
            "value": 0.122546,
            "unit": u.au,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.HZLimMoistGreenhouse": {
            "value": 1.844302e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.HZLimMaxGreenhouse": {
            "value": 0.237373,
            "unit": u.au,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.HZLimEarlyMars": {
            "value": 3.872795e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.Instellation": {
            "value": 7578.644938,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.MeanMotion": {
            "value": 6.403289e-06,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.OrbPeriod": {
            "value": 9.812434e05,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.SemiMajorAxis": {
            "value": 7.255497e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.LXUVTot": {
            "value": -1.000000,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.SurfWaterMass": {
            "value": 1.500000,
            "unit": u.TO,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.EnvelopeMass": {
            "value": 0.000300,
            "unit": u.Mearth,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.OxygenMass": {
            "value": 0.000000,
            "unit": u.bar,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.RGLimit": {
            "value": 1.763937e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.XO": {"value": 0.333333, "rtol": 1e-4},
        "log.final.ProxCenRRLim.EtaO": {"value": 0.000000, "rtol": 1e-4},
        "log.final.ProxCenRRLim.PlanetRadius": {
            "value": 1.339401,
            "unit": u.Rearth,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.OxygenMantleMass": {
            "value": 0.000000,
            "unit": u.kg,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.RadXUV": {
            "value": -1.000000,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.RadSolid": {
            "value": -1.000000,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.PresXUV": {"value": 5.000000, "rtol": 1e-4},
        "log.final.ProxCenRRLim.ScaleHeight": {
            "value": -1.000000,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.ThermTemp": {
            "value": 400.000000,
            "unit": u.K,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.AtmGasConst": {"value": 4124.000000, "rtol": 1e-4},
        "log.final.ProxCenRRLim.PresSurf": {
            "value": -1.000000,
            "unit": u.Pa,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.DEnvMassDt": {
            "value": -9.594715e06,
            "unit": u.kg / u.sec,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.FXUV": {
            "value": 7.578645,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.AtmXAbsEffH2O": {"value": 0.300000, "rtol": 1e-4},
        "log.final.ProxCenRRLim.RocheRadius": {
            "value": 1.602247e08,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.BondiRadius": {
            "value": 2.042215e08,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.HEscapeRegime": {"value": 6.000000, "rtol": 1e-4},
        "log.final.ProxCenRRLim.RRCriticalFlux": {
            "value": 30.486260,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.ProxCenRRLim.KTide": {"value": 0.920099, "rtol": 1e-4},
        "log.final.ProxCenRRLim.RGDuration": {
            "value": 0.00000e00,
            "unit": u.yr,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.Mass": {
            "value": 7.581647e24,
            "unit": u.kg,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.Radius": {
            "value": 1.336226,
            "unit": u.Rearth,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.RadGyra": {"value": 0.500000, "rtol": 1e-4},
        "log.final.ProxCenAuto.BodyType": {"value": 0.000000, "rtol": 1e-4},
        "log.final.ProxCenAuto.Density": {
            "value": 2923.891598,
            "unit": u.kg / u.m**3,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.HZLimitDryRunaway": {
            "value": 1.554176e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.HZLimRecVenus": {
            "value": 1.393855e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.HZLimRunaway": {
            "value": 0.122546,
            "unit": u.au,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.HZLimMoistGreenhouse": {
            "value": 1.844302e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.HZLimMaxGreenhouse": {
            "value": 0.237373,
            "unit": u.au,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.HZLimEarlyMars": {
            "value": 3.872795e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.Instellation": {
            "value": 7578.644938,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.MeanMotion": {
            "value": 6.403289e-06,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.OrbPeriod": {
            "value": 9.812434e05,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.SemiMajorAxis": {
            "value": 7.255497e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.LXUVTot": {
            "value": -1.000000,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.SurfWaterMass": {
            "value": 1.500000,
            "unit": u.TO,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.EnvelopeMass": {
            "value": 0.000493,
            "unit": u.Mearth,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.OxygenMass": {
            "value": 0.000000,
            "unit": u.bar,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.RGLimit": {
            "value": 1.763931e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.XO": {"value": 0.333333, "rtol": 1e-4},
        "log.final.ProxCenAuto.EtaO": {"value": 0.000000, "rtol": 1e-4},
        "log.final.ProxCenAuto.PlanetRadius": {
            "value": 1.336226,
            "unit": u.Rearth,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.OxygenMantleMass": {
            "value": 0.000000,
            "unit": u.kg,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.RadXUV": {"value": -1.000000, "unit": u.m, "rtol": 1e-4},
        "log.final.ProxCenAuto.RadSolid": {
            "value": -1.000000,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.PresXUV": {"value": 5.000000, "rtol": 1e-4},
        "log.final.ProxCenAuto.ScaleHeight": {
            "value": -1.000000,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.ThermTemp": {
            "value": 400.000000,
            "unit": u.K,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.AtmGasConst": {"value": 4124.000000, "rtol": 1e-4},
        "log.final.ProxCenAuto.PresSurf": {
            "value": -1.000000,
            "unit": u.Pa,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.DEnvMassDt": {
            "value": -4.747386e06,
            "unit": u.kg / u.sec,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.FXUV": {
            "value": 7.578645,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.AtmXAbsEffH2O": {"value": 0.300000, "rtol": 1e-4},
        "log.final.ProxCenAuto.RocheRadius": {
            "value": 1.602328e08,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.BondiRadius": {
            "value": 2.042525e08,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.HEscapeRegime": {"value": 3.000000, "rtol": 1e-4},
        "log.final.ProxCenAuto.RRCriticalFlux": {
            "value": 30.726284,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.ProxCenAuto.KTide": {"value": 0.920292, "rtol": 1e-4},
        "log.final.ProxCenAuto.RGDuration": {
            "value": 0.00000e00,
            "unit": u.yr,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.Mass": {"value": 7.578704e24, "unit": u.kg, "rtol": 1e-4},
        "log.final.LC17ELim.Radius": {
            "value": 1.063513,
            "unit": u.Rearth,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.RadGyra": {"value": 0.500000, "rtol": 1e-4},
        "log.final.LC17ELim.BodyType": {"value": 0.000000, "rtol": 1e-4},
        "log.final.LC17ELim.Density": {
            "value": 5797.014327,
            "unit": u.kg / u.m**3,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.HZLimitDryRunaway": {
            "value": 1.554176e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.HZLimRecVenus": {
            "value": 1.393855e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.HZLimRunaway": {
            "value": 0.122546,
            "unit": u.au,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.HZLimMoistGreenhouse": {
            "value": 1.844302e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.HZLimMaxGreenhouse": {
            "value": 0.237373,
            "unit": u.au,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.HZLimEarlyMars": {
            "value": 3.872795e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.Instellation": {
            "value": 7578.644938,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.MeanMotion": {
            "value": 6.403289e-06,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.OrbPeriod": {
            "value": 9.812434e05,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.SemiMajorAxis": {
            "value": 7.255497e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.LXUVTot": {
            "value": -1.000000,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.SurfWaterMass": {
            "value": 1.122761,
            "unit": u.TO,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.EnvelopeMass": {
            "value": 0.000000,
            "unit": u.Mearth,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.OxygenMass": {
            "value": 9.676785,
            "unit": u.bar,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.RGLimit": {"value": 1.763947e10, "unit": u.m, "rtol": 1e-4},
        "log.final.LC17ELim.XO": {"value": 0.341388, "rtol": 1e-4},
        "log.final.LC17ELim.EtaO": {"value": 0.813944, "rtol": 1e-4},
        "log.final.LC17ELim.PlanetRadius": {
            "value": 1.063513,
            "unit": u.Rearth,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.OxygenMantleMass": {
            "value": 0.000000,
            "unit": u.kg,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.RadXUV": {"value": 6.783190e06, "unit": u.m, "rtol": 1e-4},
        "log.final.LC17ELim.RadSolid": {
            "value": 6.783190e06,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.PresXUV": {"value": 5.000000, "rtol": 1e-4},
        "log.final.LC17ELim.ScaleHeight": {
            "value": 3.327601e05,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.ThermTemp": {
            "value": 880.000000,
            "unit": u.K,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.AtmGasConst": {"value": 4157.000000, "rtol": 1e-4},
        "log.final.LC17ELim.PresSurf": {"value": 0.000000, "unit": u.Pa, "rtol": 1e-4},
        "log.final.LC17ELim.DEnvMassDt": {
            "value": 5.562685e-309,
            "unit": u.kg / u.sec,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.FXUV": {
            "value": 7.578645,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.AtmXAbsEffH2O": {"value": 0.300000, "rtol": 1e-4},
        "log.final.LC17ELim.RocheRadius": {
            "value": 1.602121e08,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.BondiRadius": {
            "value": 2.041732e08,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.HEscapeRegime": {"value": 8.000000, "rtol": 1e-4},
        "log.final.LC17ELim.RRCriticalFlux": {
            "value": 63.063241,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.LC17ELim.KTide": {"value": 0.936530, "rtol": 1e-4},
        "log.final.LC17ELim.RGDuration": {
            "value": 0.00000e00,
            "unit": u.yr,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.Mass": {"value": 7.578704e24, "unit": u.kg, "rtol": 1e-4},
        "log.final.LC17RRLim.Radius": {
            "value": 1.063513,
            "unit": u.Rearth,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.RadGyra": {"value": 0.500000, "rtol": 1e-4},
        "log.final.LC17RRLim.BodyType": {"value": 0.000000, "rtol": 1e-4},
        "log.final.LC17RRLim.Density": {
            "value": 5797.014327,
            "unit": u.kg / u.m**3,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.HZLimitDryRunaway": {
            "value": 1.554176e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.HZLimRecVenus": {
            "value": 1.393855e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.HZLimRunaway": {
            "value": 0.122546,
            "unit": u.au,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.HZLimMoistGreenhouse": {
            "value": 1.844302e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.HZLimMaxGreenhouse": {
            "value": 0.237373,
            "unit": u.au,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.HZLimEarlyMars": {
            "value": 3.872795e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.Instellation": {
            "value": 7578.644938,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.MeanMotion": {
            "value": 6.403289e-06,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.OrbPeriod": {
            "value": 9.812434e05,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.SemiMajorAxis": {
            "value": 7.255497e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.LXUVTot": {
            "value": -1.000000,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.SurfWaterMass": {
            "value": 1.214995,
            "unit": u.TO,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.EnvelopeMass": {
            "value": 0.000000,
            "unit": u.Mearth,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.OxygenMass": {
            "value": 8.672742,
            "unit": u.bar,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.RGLimit": {
            "value": 1.763947e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.XO": {"value": 0.340018, "rtol": 1e-4},
        "log.final.LC17RRLim.EtaO": {"value": 0.809569, "rtol": 1e-4},
        "log.final.LC17RRLim.PlanetRadius": {
            "value": 1.063513,
            "unit": u.Rearth,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.OxygenMantleMass": {
            "value": 0.000000,
            "unit": u.kg,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.RadXUV": {"value": 6.783190e06, "unit": u.m, "rtol": 1e-4},
        "log.final.LC17RRLim.RadSolid": {
            "value": 6.783190e06,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.PresXUV": {"value": 5.000000, "rtol": 1e-4},
        "log.final.LC17RRLim.ScaleHeight": {
            "value": 3.327601e05,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.ThermTemp": {
            "value": 880.000000,
            "unit": u.K,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.AtmGasConst": {"value": 4157.000000, "rtol": 1e-4},
        "log.final.LC17RRLim.PresSurf": {"value": 0.000000, "unit": u.Pa, "rtol": 1e-4},
        "log.final.LC17RRLim.DEnvMassDt": {
            "value": 5.562685e-309,
            "unit": u.kg / u.sec,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.FXUV": {
            "value": 7.578645,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.AtmXAbsEffH2O": {"value": 0.300000, "rtol": 1e-4},
        "log.final.LC17RRLim.RocheRadius": {
            "value": 1.602121e08,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.BondiRadius": {
            "value": 2.041732e08,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.HEscapeRegime": {"value": 8.000000, "rtol": 1e-4},
        "log.final.LC17RRLim.RRCriticalFlux": {
            "value": 63.063241,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.LC17RRLim.KTide": {"value": 0.936530, "rtol": 1e-4},
        "log.final.LC17RRLim.RGDuration": {
            "value": 0.00000e00,
            "unit": u.yr,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.Mass": {"value": 7.578704e24, "unit": u.kg, "rtol": 1e-4},
        "log.final.LC17Auto.Radius": {
            "value": 1.063513,
            "unit": u.Rearth,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.RadGyra": {"value": 0.500000, "rtol": 1e-4},
        "log.final.LC17Auto.BodyType": {"value": 0.000000, "rtol": 1e-4},
        "log.final.LC17Auto.Density": {
            "value": 5797.014327,
            "unit": u.kg / u.m**3,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.HZLimitDryRunaway": {
            "value": 1.554176e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.HZLimRecVenus": {
            "value": 1.393855e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.HZLimRunaway": {
            "value": 0.122546,
            "unit": u.au,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.HZLimMoistGreenhouse": {
            "value": 1.844302e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.HZLimMaxGreenhouse": {
            "value": 0.237373,
            "unit": u.au,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.HZLimEarlyMars": {
            "value": 3.872795e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.Instellation": {
            "value": 7578.644938,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.MeanMotion": {
            "value": 6.403289e-06,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.OrbPeriod": {
            "value": 9.812434e05,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.SemiMajorAxis": {
            "value": 7.255497e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.LXUVTot": {
            "value": -1.000000,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.SurfWaterMass": {
            "value": 1.214365,
            "unit": u.TO,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.EnvelopeMass": {
            "value": 0.000000,
            "unit": u.Mearth,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.OxygenMass": {
            "value": 8.681141,
            "unit": u.bar,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.RGLimit": {"value": 1.763947e10, "unit": u.m, "rtol": 1e-4},
        "log.final.LC17Auto.XO": {"value": 0.340028, "rtol": 1e-4},
        "log.final.LC17Auto.EtaO": {"value": 0.809600, "rtol": 1e-4},
        "log.final.LC17Auto.PlanetRadius": {
            "value": 1.063513,
            "unit": u.Rearth,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.OxygenMantleMass": {
            "value": 0.000000,
            "unit": u.kg,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.RadXUV": {"value": 6.783190e06, "unit": u.m, "rtol": 1e-4},
        "log.final.LC17Auto.RadSolid": {
            "value": 6.783190e06,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.PresXUV": {"value": 5.000000, "rtol": 1e-4},
        "log.final.LC17Auto.ScaleHeight": {
            "value": 3.327601e05,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.ThermTemp": {
            "value": 880.000000,
            "unit": u.K,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.AtmGasConst": {"value": 4157.000000, "rtol": 1e-4},
        "log.final.LC17Auto.PresSurf": {"value": 0.000000, "unit": u.Pa, "rtol": 1e-4},
        "log.final.LC17Auto.DEnvMassDt": {
            "value": 5.562685e-309,
            "unit": u.kg / u.sec,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.FXUV": {
            "value": 7.578645,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.AtmXAbsEffH2O": {"value": 0.300000, "rtol": 1e-4},
        "log.final.LC17Auto.RocheRadius": {
            "value": 1.602121e08,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.BondiRadius": {
            "value": 2.041732e08,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.HEscapeRegime": {"value": 8.000000, "rtol": 1e-4},
        "log.final.LC17Auto.RRCriticalFlux": {
            "value": 63.063241,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.LC17Auto.KTide": {"value": 0.936530, "rtol": 1e-4},
        "log.final.LC17Auto.RGDuration": {
            "value": 0.00000e00,
            "unit": u.yr,
            "rtol": 1e-4,
        },
    }
)
class TestHabEvapCore(Benchmark):
    pass
