import astropy.units as u
from benchmark import Benchmark, benchmark


@benchmark(
    {
        "log.initial.system.Age": {"value": 0.00000, "unit": u.sec},
        "log.initial.system.Time": {"value": 0.00000, "unit": u.sec},
        "log.initial.system.TotAngMom": {
            "value": 1.77136e41,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.system.TotEnergy": {"value": -3.10077e46, "unit": u.Joule},
        "log.initial.system.PotEnergy": {"value": -3.10432e46, "unit": u.Joule},
        "log.initial.system.KinEnergy": {"value": 3.55253e43, "unit": u.Joule},
        "log.initial.system.DeltaTime": {"value": 3155.76000, "unit": u.sec},
        "log.initial.Pulsar.Mass": {"value": 2.78424e30, "unit": u.kg},
        "log.initial.Pulsar.Radius": {"value": 1.00000e04, "unit": u.m},
        "log.initial.Pulsar.RadGyra": {"value": 0.50000},
        "log.initial.Pulsar.RotAngMom": {
            "value": 7.03246e40,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.Pulsar.RotVel": {"value": 1.01032e07, "unit": u.m / u.sec},
        "log.initial.Pulsar.BodyType": {"value": 0.00000},
        "log.initial.Pulsar.RotRate": {"value": 1010.32196, "unit": 1 / u.sec},
        "log.initial.Pulsar.RotPer": {"value": 0.00622, "unit": u.sec},
        "log.initial.Pulsar.Density": {"value": 6.64684e17, "unit": u.kg / u.m**3},
        "log.initial.Pulsar.HZLimitDryRunaway": {"value": 4.29384e09, "unit": u.m},
        "log.initial.Pulsar.HZLimRecVenus": {"value": 3.53836e09, "unit": u.m},
        "log.initial.Pulsar.HZLimRunaway": {"value": 4.62043e09, "unit": u.m},
        "log.initial.Pulsar.HZLimMoistGreenhouse": {"value": 4.68180e09, "unit": u.m},
        "log.initial.Pulsar.HZLimMaxGreenhouse": {"value": 7.93585e09, "unit": u.m},
        "log.initial.Pulsar.HZLimEarlyMars": {"value": 8.65866e09, "unit": u.m},
        "log.initial.Pulsar.Instellation": {
            "value": -1.00000,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.Pulsar.Eccentricity": {"value": -1.00000},
        "log.initial.Pulsar.MeanMotion": {"value": -1.00000, "unit": 1 / u.sec},
        "log.initial.Pulsar.OrbPeriod": {"value": -1.00000, "unit": u.sec},
        "log.initial.Pulsar.SemiMajorAxis": {"value": -1.00000, "unit": u.m},
        "log.initial.Pulsar.CriticalSemiMajorAxis": {"value": -1.00000, "unit": u.m},
        "log.initial.Pulsar.COPP": {"value": 0.00000},
        "log.initial.Pulsar.OrbAngMom": {
            "value": 6.98025e34,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.Pulsar.ArgP": {"value": 0.00000, "unit": u.rad},
        "log.initial.Pulsar.MeanAnomaly": {"value": 0.00000, "unit": u.rad},
        "log.initial.Pulsar.Inc": {"value": 0.00000, "unit": u.rad},
        "log.initial.Pulsar.LongA": {"value": 0.00000, "unit": u.rad},
        "log.initial.Pulsar.MeanLongitude": {"value": -1.00000, "unit": u.rad},
        "log.initial.Pulsar.LongP": {"value": 0.00000, "unit": u.rad},
        "log.initial.Pulsar.LXUVTot": {"value": 3.84600e23, "unit": u.kg / u.sec**3},
        "log.initial.Pulsar.TotOrbEnergy": {"value": -9.47454e34, "unit": u.Joule},
        "log.initial.Pulsar.OrbPotEnergy": {"value": -1.00000, "unit": u.Joule},
        "log.initial.Pulsar.LostEnergy": {"value": 5.56268e-309, "unit": u.Joule},
        "log.initial.Pulsar.LostAngMom": {
            "value": 5.56268e-309,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.Pulsar.Luminosity": {"value": 3.84600e23, "unit": u.W},
        "log.initial.Pulsar.LXUVStellar": {"value": 3.84600e23, "unit": u.W},
        "log.initial.Pulsar.Temperature": {"value": 5778.00000, "unit": u.K},
        "log.initial.Pulsar.LXUVFrac": {"value": 1.00000},
        "log.initial.Pulsar.RossbyNumber": {"value": 5.63306e-09},
        "log.initial.Pulsar.DRotPerDtStellar": {"value": 1.20085e-34},
        "log.initial.Pulsar.PositionXSpiNBody": {"value": 2.59713e05},
        "log.initial.Pulsar.PositionYSpiNBody": {"value": -8.20857e04},
        "log.initial.Pulsar.PositionZSpiNBody": {"value": -2.94022e04},
        "log.initial.Pulsar.VelXSpiNBody": {"value": -0.07553},
        "log.initial.Pulsar.VelYSpiNBody": {"value": 0.08947},
        "log.initial.Pulsar.VelZSpiNBody": {"value": 0.07787},
        "log.initial.Pulsar.SpiNBodyInc": {"value": 0.00000, "unit": u.rad},
        "log.initial.Pulsar.SpiNBodyLongA": {"value": 0.00000, "unit": u.rad},
        "log.initial.A.Mass": {"value": 1.02000, "unit": u.Mearth},
        "log.initial.A.Radius": {"value": 3.81253e08, "unit": u.m},
        "log.initial.A.RadGyra": {"value": 0.50000},
        "log.initial.A.BodyType": {"value": 0.00000},
        "log.initial.A.Density": {"value": 0.02624, "unit": u.kg / u.m**3},
        "log.initial.A.HZLimitDryRunaway": {"value": 4.29384e09, "unit": u.m},
        "log.initial.A.HZLimRecVenus": {"value": 3.53836e09, "unit": u.m},
        "log.initial.A.HZLimRunaway": {"value": 4.62043e09, "unit": u.m},
        "log.initial.A.HZLimMoistGreenhouse": {"value": 4.68180e09, "unit": u.m},
        "log.initial.A.HZLimMaxGreenhouse": {"value": 7.93585e09, "unit": u.m},
        "log.initial.A.HZLimEarlyMars": {"value": 8.65866e09, "unit": u.m},
        "log.initial.A.Instellation": {"value": 38.48805, "unit": u.kg / u.sec**3},
        "log.initial.A.Eccentricity": {"value": 0.00000},
        "log.initial.A.MeanMotion": {"value": 2.87873e-06, "unit": 1 / u.sec},
        "log.initial.A.OrbPeriod": {"value": 2.18263e06, "unit": u.sec},
        "log.initial.A.SemiMajorAxis": {"value": 2.81992e10, "unit": u.m},
        "log.initial.A.COPP": {"value": 0.00000},
        "log.initial.A.OrbAngMom": {
            "value": 1.39448e40,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.A.ArgP": {"value": 0.00000, "unit": u.rad},
        "log.initial.A.MeanAnomaly": {"value": 0.24871, "unit": u.rad},
        "log.initial.A.Inc": {"value": 0.87266, "unit": u.rad},
        "log.initial.A.LongA": {"value": 0.00000, "unit": u.rad},
        "log.initial.A.MeanLongitude": {"value": 0.24871, "unit": u.rad},
        "log.initial.A.LongP": {"value": 0.00000, "unit": u.rad},
        "log.initial.A.LXUVTot": {"value": -1.00000, "unit": u.kg / u.sec**3},
        "log.initial.A.TotOrbEnergy": {"value": -9.47454e34, "unit": u.Joule},
        "log.initial.A.OrbPotEnergy": {"value": -2.68821e29, "unit": u.Joule},
        "log.initial.A.SurfWaterMass": {"value": 0.00000, "unit": u.kg},
        "log.initial.A.EnvelopeMass": {"value": 1.00000, "unit": u.Mearth},
        "log.initial.A.OxygenMass": {"value": 0.00000, "unit": u.kg},
        "log.initial.A.RGLimit": {"value": 4.49538e09, "unit": u.m},
        "log.initial.A.XO": {"value": 0.00000},
        "log.initial.A.EtaO": {"value": 0.00000},
        "log.initial.A.PlanetRadius": {"value": 59.77534, "unit": u.Rearth},
        "log.initial.A.OxygenMantleMass": {"value": 0.00000, "unit": u.kg},
        "log.initial.A.RadXUV": {"value": -1.00000, "unit": u.m},
        "log.initial.A.RadSolid": {"value": -1.00000, "unit": u.m},
        "log.initial.A.PresXUV": {"value": 5.00000},
        "log.initial.A.ScaleHeight": {"value": -1.00000, "unit": u.m},
        "log.initial.A.ThermTemp": {"value": 400.00000, "unit": u.K},
        "log.initial.A.AtmGasConst": {"value": 4124.00000},
        "log.initial.A.PresSurf": {"value": -1.00000, "unit": u.Pa},
        "log.initial.A.DEnvMassDt": {"value": -1.64808e12, "unit": u.kg / u.sec},
        "log.initial.A.FXUV": {"value": 38.48805, "unit": u.W / u.m**2},
        "log.initial.A.AtmXAbsEffH2O": {"value": 0.30000},
        "log.initial.A.RocheRadius": {"value": 2.53828e08, "unit": u.m},
        "log.initial.A.BondiRadius": {"value": 7.41067e09, "unit": u.m},
        "log.initial.A.HEscapeRegime": {"value": 3.00000},
        "log.initial.A.RRCriticalFlux": {"value": 0.00059, "unit": u.W / u.m**2},
        "log.initial.A.CrossoverMass": {"value": 0.00000, "unit": u.kg},
        "log.initial.A.WaterEscapeRegime": {"value": 8.00000},
        "log.initial.A.FXUVCRITDRAG": {"value": 1.29749e-06, "unit": u.W / u.m**2},
        "log.initial.A.HREFFLUX": {"value": 1.63010e21, "unit": 1 / u.m**2 / u.sec},
        "log.initial.A.XO2": {"value": 0.00000},
        "log.initial.A.XH2O": {"value": 0.00000},
        "log.initial.A.HDiffFlux": {"value": 5.41620e13, "unit": 1 / u.m**2 / u.sec},
        "log.initial.A.HRefODragMod": {"value": 1.00000},
        "log.initial.A.KTide": {"value": 1.00000},
        "log.initial.A.RGDuration": {"value": 0.00000e00, "unit": u.yr},
        "log.initial.A.PositionXSpiNBody": {"value": 2.73318e10},
        "log.initial.A.PositionYSpiNBody": {"value": 4.46172e09},
        "log.initial.A.PositionZSpiNBody": {"value": 5.31733e09},
        "log.initial.A.VelXSpiNBody": {"value": -1.99823e04},
        "log.initial.A.VelYSpiNBody": {"value": 5.05746e04},
        "log.initial.A.VelZSpiNBody": {"value": 6.02725e04},
        "log.initial.A.SpiNBodyInc": {"value": 0.87266, "unit": u.rad},
        "log.initial.A.SpiNBodyLongA": {"value": 0.00000, "unit": u.rad},
        "log.initial.B.Mass": {"value": 4.25000, "unit": u.Mearth},
        "log.initial.B.Radius": {"value": 8.59523e07, "unit": u.m},
        "log.initial.B.RadGyra": {"value": 0.50000},
        "log.initial.B.BodyType": {"value": 0.00000},
        "log.initial.B.Density": {"value": 9.54246, "unit": u.kg / u.m**3},
        "log.initial.B.HZLimitDryRunaway": {"value": 4.29458e09, "unit": u.m},
        "log.initial.B.HZLimRecVenus": {"value": 3.53836e09, "unit": u.m},
        "log.initial.B.HZLimRunaway": {"value": 4.62043e09, "unit": u.m},
        "log.initial.B.HZLimMoistGreenhouse": {"value": 4.68180e09, "unit": u.m},
        "log.initial.B.HZLimMaxGreenhouse": {"value": 7.93585e09, "unit": u.m},
        "log.initial.B.HZLimEarlyMars": {"value": 8.65866e09, "unit": u.m},
        "log.initial.B.Instellation": {"value": 10.58224, "unit": u.kg / u.sec**3},
        "log.initial.B.Eccentricity": {"value": 0.01860},
        "log.initial.B.MeanMotion": {"value": 1.09291e-06, "unit": 1 / u.sec},
        "log.initial.B.OrbPeriod": {"value": 5.74904e06, "unit": u.sec},
        "log.initial.B.SemiMajorAxis": {"value": 5.37834e10, "unit": u.m},
        "log.initial.B.COPP": {"value": -0.00000},
        "log.initial.B.OrbAngMom": {
            "value": 8.02284e40,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.B.ArgP": {"value": 0.00000, "unit": u.rad},
        "log.initial.B.MeanAnomaly": {"value": 0.09442, "unit": u.rad},
        "log.initial.B.Inc": {"value": 0.92502, "unit": u.rad},
        "log.initial.B.LongA": {"value": 0.00000, "unit": u.rad},
        "log.initial.B.MeanLongitude": {"value": 4.46473, "unit": u.rad},
        "log.initial.B.LongP": {"value": 4.37030, "unit": u.rad},
        "log.initial.B.LXUVTot": {"value": -1.00000, "unit": u.kg / u.sec**3},
        "log.initial.B.TotOrbEnergy": {"value": -9.47454e34, "unit": u.Joule},
        "log.initial.B.OrbPotEnergy": {"value": -3.40383e29, "unit": u.Joule},
        "log.initial.B.SurfWaterMass": {"value": 0.00000, "unit": u.kg},
        "log.initial.B.EnvelopeMass": {"value": 0.81818, "unit": u.Mearth},
        "log.initial.B.OxygenMass": {"value": 0.00000, "unit": u.kg},
        "log.initial.B.RGLimit": {"value": 4.35520e09, "unit": u.m},
        "log.initial.B.XO": {"value": 0.00000},
        "log.initial.B.EtaO": {"value": 0.00000},
        "log.initial.B.PlanetRadius": {"value": 13.47617, "unit": u.Rearth},
        "log.initial.B.OxygenMantleMass": {"value": 0.00000, "unit": u.kg},
        "log.initial.B.RadXUV": {"value": -1.00000, "unit": u.m},
        "log.initial.B.RadSolid": {"value": -1.00000, "unit": u.m},
        "log.initial.B.PresXUV": {"value": 5.00000},
        "log.initial.B.ScaleHeight": {"value": -1.00000, "unit": u.m},
        "log.initial.B.ThermTemp": {"value": 400.00000, "unit": u.K},
        "log.initial.B.AtmGasConst": {"value": 4124.00000},
        "log.initial.B.PresSurf": {"value": -1.00000, "unit": u.Pa},
        "log.initial.B.DEnvMassDt": {"value": -1.49210e09, "unit": u.kg / u.sec},
        "log.initial.B.FXUV": {"value": 10.58224, "unit": u.W / u.m**2},
        "log.initial.B.AtmXAbsEffH2O": {"value": 0.30000},
        "log.initial.B.RocheRadius": {"value": 7.79017e08, "unit": u.m},
        "log.initial.B.BondiRadius": {"value": 2.23584e10, "unit": u.m},
        "log.initial.B.HEscapeRegime": {"value": 3.00000},
        "log.initial.B.RRCriticalFlux": {"value": 0.62208, "unit": u.W / u.m**2},
        "log.initial.B.CrossoverMass": {"value": 0.00000, "unit": u.kg},
        "log.initial.B.WaterEscapeRegime": {"value": 8.00000},
        "log.initial.B.FXUVCRITDRAG": {"value": 0.00197, "unit": u.W / u.m**2},
        "log.initial.B.HREFFLUX": {"value": 2.90366e19, "unit": 1 / u.m**2 / u.sec},
        "log.initial.B.XO2": {"value": 0.00000},
        "log.initial.B.XH2O": {"value": 0.00000},
        "log.initial.B.HDiffFlux": {"value": 4.44012e15, "unit": 1 / u.m**2 / u.sec},
        "log.initial.B.HRefODragMod": {"value": 1.00000},
        "log.initial.B.KTide": {"value": 0.83517},
        "log.initial.B.RGDuration": {"value": 0.00000e00, "unit": u.yr},
        "log.initial.B.PositionXSpiNBody": {"value": -1.27562e10},
        "log.initial.B.PositionYSpiNBody": {"value": -3.08269e10},
        "log.initial.B.PositionZSpiNBody": {"value": -4.09087e10},
        "log.initial.B.VelXSpiNBody": {"value": 5.80783e04},
        "log.initial.B.VelYSpiNBody": {"value": -8770.71269},
        "log.initial.B.VelZSpiNBody": {"value": -1.16392e04},
        "log.initial.B.SpiNBodyInc": {"value": 0.92502, "unit": u.rad},
        "log.initial.B.SpiNBodyLongA": {"value": 0.00000, "unit": u.rad},
        "log.initial.C.Mass": {"value": 3.87300, "unit": u.Mearth},
        "log.initial.C.Radius": {"value": 9.65087e07, "unit": u.m},
        "log.initial.C.RadGyra": {"value": 0.50000},
        "log.initial.C.BodyType": {"value": 0.00000},
        "log.initial.C.Density": {"value": 6.14317, "unit": u.kg / u.m**3},
        "log.initial.C.HZLimitDryRunaway": {"value": 4.29520e09, "unit": u.m},
        "log.initial.C.HZLimRecVenus": {"value": 3.53836e09, "unit": u.m},
        "log.initial.C.HZLimRunaway": {"value": 4.62043e09, "unit": u.m},
        "log.initial.C.HZLimMoistGreenhouse": {"value": 4.68180e09, "unit": u.m},
        "log.initial.C.HZLimMaxGreenhouse": {"value": 7.93585e09, "unit": u.m},
        "log.initial.C.HZLimEarlyMars": {"value": 8.65866e09, "unit": u.m},
        "log.initial.C.Instellation": {"value": 6.29854, "unit": u.kg / u.sec**3},
        "log.initial.C.Eccentricity": {"value": 0.02520},
        "log.initial.C.MeanMotion": {"value": 7.40515e-07, "unit": 1 / u.sec},
        "log.initial.C.OrbPeriod": {"value": 8.48488e06, "unit": u.sec},
        "log.initial.C.SemiMajorAxis": {"value": 6.97186e10, "unit": u.m},
        "log.initial.C.COPP": {"value": 0.00000},
        "log.initial.C.OrbAngMom": {
            "value": 8.32287e40,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.C.ArgP": {"value": 0.00000, "unit": u.rad},
        "log.initial.C.MeanAnomaly": {"value": 0.06388, "unit": u.rad},
        "log.initial.C.Inc": {"value": 0.82030, "unit": u.rad},
        "log.initial.C.LongA": {"value": 0.05690, "unit": u.rad},
        "log.initial.C.MeanLongitude": {"value": 1.95407, "unit": u.rad},
        "log.initial.C.LongP": {"value": 1.89019, "unit": u.rad},
        "log.initial.C.LXUVTot": {"value": -1.00000, "unit": u.kg / u.sec**3},
        "log.initial.C.TotOrbEnergy": {"value": -9.47454e34, "unit": u.Joule},
        "log.initial.C.OrbPotEnergy": {"value": 0.00000, "unit": u.Joule},
        "log.initial.C.SurfWaterMass": {"value": 0.00000, "unit": u.kg},
        "log.initial.C.EnvelopeMass": {"value": 0.81818, "unit": u.Mearth},
        "log.initial.C.OxygenMass": {"value": 0.00000, "unit": u.kg},
        "log.initial.C.RGLimit": {"value": 4.36359e09, "unit": u.m},
        "log.initial.C.XO": {"value": 0.00000},
        "log.initial.C.EtaO": {"value": 0.00000},
        "log.initial.C.PlanetRadius": {"value": 15.13127, "unit": u.Rearth},
        "log.initial.C.OxygenMantleMass": {"value": 0.00000, "unit": u.kg},
        "log.initial.C.RadXUV": {"value": -1.00000, "unit": u.m},
        "log.initial.C.RadSolid": {"value": -1.00000, "unit": u.m},
        "log.initial.C.PresXUV": {"value": 5.00000},
        "log.initial.C.ScaleHeight": {"value": -1.00000, "unit": u.m},
        "log.initial.C.ThermTemp": {"value": 400.00000, "unit": u.K},
        "log.initial.C.AtmGasConst": {"value": 4124.00000},
        "log.initial.C.PresSurf": {"value": -1.00000, "unit": u.Pa},
        "log.initial.C.DEnvMassDt": {"value": -1.35130e09, "unit": u.kg / u.sec},
        "log.initial.C.FXUV": {"value": 6.29854, "unit": u.W / u.m**2},
        "log.initial.C.AtmXAbsEffH2O": {"value": 0.30000},
        "log.initial.C.RocheRadius": {"value": 9.79039e08, "unit": u.m},
        "log.initial.C.BondiRadius": {"value": 1.78957e10, "unit": u.m},
        "log.initial.C.HEscapeRegime": {"value": 3.00000},
        "log.initial.C.RRCriticalFlux": {"value": 0.38036, "unit": u.W / u.m**2},
        "log.initial.C.CrossoverMass": {"value": 0.00000, "unit": u.kg},
        "log.initial.C.WaterEscapeRegime": {"value": 8.00000},
        "log.initial.C.FXUVCRITDRAG": {"value": 0.00115, "unit": u.W / u.m**2},
        "log.initial.C.HREFFLUX": {"value": 2.08584e19, "unit": 1 / u.m**2 / u.sec},
        "log.initial.C.XO2": {"value": 0.00000},
        "log.initial.C.XH2O": {"value": 0.00000},
        "log.initial.C.HDiffFlux": {"value": 3.20948e15, "unit": 1 / u.m**2 / u.sec},
        "log.initial.C.HRefODragMod": {"value": 1.00000},
        "log.initial.C.KTide": {"value": 0.85262},
        "log.initial.C.RGDuration": {"value": 0.00000e00, "unit": u.yr},
        "log.initial.C.PositionXSpiNBody": {"value": -2.44624e10},
        "log.initial.C.PositionYSpiNBody": {"value": 4.25334e10},
        "log.initial.C.PositionZSpiNBody": {"value": 4.70296e10},
        "log.initial.C.VelXSpiNBody": {"value": -4.93768e04},
        "log.initial.C.VelYSpiNBody": {"value": -1.44647e04},
        "log.initial.C.VelZSpiNBody": {"value": -1.24753e04},
        "log.initial.C.SpiNBodyInc": {"value": 0.82030, "unit": u.rad},
        "log.initial.C.SpiNBodyLongA": {"value": 0.05690, "unit": u.rad},
        "log.final.system.Age": {"value": 3.15576e09, "unit": u.sec, "rtol": 1e-4},
        "log.final.system.Time": {"value": 3.15576e09, "unit": u.sec, "rtol": 1e-4},
        "log.final.system.TotAngMom": {
            "value": 1.77125e41,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.system.TotEnergy": {
            "value": -3.10077e46,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.system.PotEnergy": {
            "value": -3.10432e46,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.system.KinEnergy": {
            "value": 3.55253e43,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.Mass": {"value": 2.78424e30, "unit": u.kg, "rtol": 1e-4},
        "log.final.Pulsar.Radius": {"value": 1.00000e04, "unit": u.m, "rtol": 1e-4},
        "log.final.Pulsar.RadGyra": {"value": 0.50000, "rtol": 1e-4},
        "log.final.Pulsar.RotAngMom": {
            "value": 7.03246e40,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.RotVel": {
            "value": 1.01032e07,
            "unit": u.m / u.sec,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.BodyType": {"value": 0.00000, "rtol": 1e-4},
        "log.final.Pulsar.RotRate": {
            "value": 1010.32196,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.RotPer": {"value": 0.00622, "unit": u.sec, "rtol": 1e-4},
        "log.final.Pulsar.Density": {
            "value": 6.64684e17,
            "unit": u.kg / u.m**3,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.HZLimitDryRunaway": {
            "value": 4.29384e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.HZLimRecVenus": {
            "value": 3.53836e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.HZLimRunaway": {
            "value": 4.62043e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.HZLimMoistGreenhouse": {
            "value": 4.68180e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.HZLimMaxGreenhouse": {
            "value": 7.93585e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.HZLimEarlyMars": {
            "value": 8.65866e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.Instellation": {
            "value": -1.00000,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.Eccentricity": {"value": -1.00000, "rtol": 1e-4},
        "log.final.Pulsar.MeanMotion": {
            "value": -1.00000,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.OrbPeriod": {"value": -1.00000, "unit": u.sec, "rtol": 1e-4},
        "log.final.Pulsar.SemiMajorAxis": {
            "value": -1.00000,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.CriticalSemiMajorAxis": {
            "value": -1.00000,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.COPP": {"value": 0.00000, "rtol": 1e-4},
        "log.final.Pulsar.OrbAngMom": {
            "value": 5.09474e34,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.ArgP": {"value": 0.00000, "unit": u.rad, "rtol": 1e-4},
        "log.final.Pulsar.MeanAnomaly": {"value": 0.00000, "unit": u.rad, "rtol": 1e-4},
        "log.final.Pulsar.Inc": {"value": 0.00000, "unit": u.rad, "rtol": 1e-4},
        "log.final.Pulsar.LongA": {"value": 0.00000, "unit": u.rad, "rtol": 1e-4},
        "log.final.Pulsar.MeanLongitude": {
            "value": -1.00000,
            "unit": u.rad,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.LongP": {"value": 0.00000, "unit": u.rad, "rtol": 1e-4},
        "log.final.Pulsar.LXUVTot": {
            "value": 3.84600e23,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.TotOrbEnergy": {
            "value": -9.47283e34,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.OrbPotEnergy": {
            "value": -1.00000,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.LostEnergy": {
            "value": 4.32952e21,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.LostAngMom": {
            "value": 4.28529e18,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.Luminosity": {"value": 3.84600e23, "unit": u.W, "rtol": 1e-4},
        "log.final.Pulsar.LXUVStellar": {
            "value": 3.84600e23,
            "unit": u.W,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.Temperature": {
            "value": 5778.00000,
            "unit": u.K,
            "rtol": 1e-4,
        },
        "log.final.Pulsar.LXUVFrac": {"value": 1.00000, "rtol": 1e-4},
        "log.final.Pulsar.RossbyNumber": {"value": 5.63306e-09, "rtol": 1e-4},
        "log.final.Pulsar.DRotPerDtStellar": {"value": 1.20085e-34, "rtol": 1e-4},
        "log.final.Pulsar.PositionXSpiNBody": {"value": 1.83395e05, "rtol": 1e-4},
        "log.final.Pulsar.PositionYSpiNBody": {"value": -1.45367e05, "rtol": 1e-4},
        "log.final.Pulsar.PositionZSpiNBody": {"value": -9.16105e04, "rtol": 1e-4},
        "log.final.Pulsar.VelXSpiNBody": {"value": -0.08613, "rtol": 1e-4},
        "log.final.Pulsar.VelYSpiNBody": {"value": 0.10424, "rtol": 1e-4},
        "log.final.Pulsar.VelZSpiNBody": {"value": 0.12387, "rtol": 1e-4},
        "log.final.Pulsar.SpiNBodyInc": {"value": 0.00000, "unit": u.rad, "rtol": 1e-4},
        "log.final.Pulsar.SpiNBodyLongA": {
            "value": 0.00000,
            "unit": u.rad,
            "rtol": 1e-4,
        },
        "log.final.A.Mass": {"value": 1.01913, "unit": u.Mearth, "rtol": 1e-4},
        "log.final.A.Radius": {"value": 3.81444e08, "unit": u.m, "rtol": 1e-4},
        "log.final.A.RadGyra": {"value": 0.50000, "rtol": 1e-4},
        "log.final.A.BodyType": {"value": 0.00000, "rtol": 1e-4},
        "log.final.A.Density": {
            "value": 0.02618,
            "unit": u.kg / u.m**3,
            "rtol": 1e-4,
        },
        "log.final.A.HZLimitDryRunaway": {
            "value": 4.29384e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.A.HZLimRecVenus": {"value": 3.53836e09, "unit": u.m, "rtol": 1e-4},
        "log.final.A.HZLimRunaway": {"value": 4.62043e09, "unit": u.m, "rtol": 1e-4},
        "log.final.A.HZLimMoistGreenhouse": {
            "value": 4.68180e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.A.HZLimMaxGreenhouse": {
            "value": 7.93585e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.A.HZLimEarlyMars": {"value": 8.65866e09, "unit": u.m, "rtol": 1e-4},
        "log.final.A.Instellation": {
            "value": 38.48814,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.A.Eccentricity": {"value": 0.00014, "rtol": 1e-4},
        "log.final.A.MeanMotion": {
            "value": 2.87873e-06,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.A.OrbPeriod": {"value": 2.18262e06, "unit": u.sec, "rtol": 1e-4},
        "log.final.A.SemiMajorAxis": {"value": 2.81992e10, "unit": u.m, "rtol": 1e-4},
        "log.final.A.COPP": {"value": 0.00000, "rtol": 1e-4},
        "log.final.A.OrbAngMom": {
            "value": 1.39329e40,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.A.ArgP": {"value": 2.54006, "unit": u.rad, "rtol": 1e-4},
        "log.final.A.MeanAnomaly": {"value": 3.02267, "unit": u.rad, "rtol": 1e-4},
        "log.final.A.Inc": {"value": 0.87248, "unit": u.rad, "rtol": 1e-4},
        "log.final.A.LongA": {"value": 0.00074, "unit": u.rad, "rtol": 1e-4},
        "log.final.A.MeanLongitude": {"value": 5.56347, "unit": u.rad, "rtol": 1e-4},
        "log.final.A.LongP": {"value": 2.54081, "unit": u.rad, "rtol": 1e-4},
        "log.final.A.LXUVTot": {
            "value": -1.00000,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.A.TotOrbEnergy": {
            "value": -9.47283e34,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.A.OrbPotEnergy": {
            "value": -2.78755e29,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.A.SurfWaterMass": {"value": 0.00000, "unit": u.kg, "rtol": 1e-4},
        "log.final.A.EnvelopeMass": {"value": 0.99913, "unit": u.Mearth, "rtol": 1e-4},
        "log.final.A.OxygenMass": {"value": 0.00000, "unit": u.kg, "rtol": 1e-4},
        "log.final.A.RGLimit": {"value": 4.49547e09, "unit": u.m, "rtol": 1e-4},
        "log.final.A.XO": {"value": 0.00000, "rtol": 1e-4},
        "log.final.A.EtaO": {"value": 0.00000, "rtol": 1e-4},
        "log.final.A.PlanetRadius": {"value": 59.80530, "unit": u.Rearth, "rtol": 1e-4},
        "log.final.A.OxygenMantleMass": {"value": 0.00000, "unit": u.kg, "rtol": 1e-4},
        "log.final.A.RadXUV": {"value": -1.00000, "unit": u.m, "rtol": 1e-4},
        "log.final.A.RadSolid": {"value": -1.00000, "unit": u.m, "rtol": 1e-4},
        "log.final.A.PresXUV": {"value": 5.00000, "rtol": 1e-4},
        "log.final.A.ScaleHeight": {"value": -1.00000, "unit": u.m, "rtol": 1e-4},
        "log.final.A.ThermTemp": {"value": 400.00000, "unit": u.K, "rtol": 1e-4},
        "log.final.A.AtmGasConst": {"value": 4124.00000, "rtol": 1e-4},
        "log.final.A.PresSurf": {"value": -1.00000, "unit": u.Pa, "rtol": 1e-4},
        "log.final.A.DEnvMassDt": {
            "value": -1.65197e12,
            "unit": u.kg / u.sec,
            "rtol": 1e-4,
        },
        "log.final.A.FXUV": {"value": 38.48814, "unit": u.W / u.m**2, "rtol": 1e-4},
        "log.final.A.AtmXAbsEffH2O": {"value": 0.30000, "rtol": 1e-4},
        "log.final.A.RocheRadius": {"value": 2.53755e08, "unit": u.m, "rtol": 1e-4},
        "log.final.A.BondiRadius": {"value": 7.40434e09, "unit": u.m, "rtol": 1e-4},
        "log.final.A.HEscapeRegime": {"value": 3.00000, "rtol": 1e-4},
        "log.final.A.RRCriticalFlux": {
            "value": 0.00059,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.A.CrossoverMass": {"value": 0.00000, "unit": u.kg, "rtol": 1e-4},
        "log.final.A.WaterEscapeRegime": {"value": 8.00000, "rtol": 1e-4},
        "log.final.A.FXUVCRITDRAG": {
            "value": 1.29333e-06,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.A.HREFFLUX": {
            "value": 1.63231e21,
            "unit": 1 / u.m**2 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.A.XO2": {"value": 0.00000, "rtol": 1e-4},
        "log.final.A.XH2O": {"value": 0.00000, "rtol": 1e-4},
        "log.final.A.HDiffFlux": {
            "value": 5.40615e13,
            "unit": 1 / u.m**2 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.A.HRefODragMod": {"value": 1.00000, "rtol": 1e-4},
        "log.final.A.KTide": {"value": 1.00000, "rtol": 1e-4},
        "log.final.A.RGDuration": {"value": 1.00000e-04, "unit": u.yr, "rtol": 1e-4},
        "log.final.A.PositionXSpiNBody": {"value": 2.12045e10, "rtol": 1e-4},
        "log.final.A.PositionYSpiNBody": {"value": -1.19465e10, "rtol": 1e-4},
        "log.final.A.PositionZSpiNBody": {"value": -1.42507e10, "rtol": 1e-4},
        "log.final.A.VelXSpiNBody": {"value": 5.35175e04, "rtol": 1e-4},
        "log.final.A.VelYSpiNBody": {"value": 3.92569e04, "rtol": 1e-4},
        "log.final.A.VelZSpiNBody": {"value": 4.67201e04, "rtol": 1e-4},
        "log.final.A.SpiNBodyInc": {"value": 0.87248, "unit": u.rad, "rtol": 1e-4},
        "log.final.A.SpiNBodyLongA": {"value": 0.00074, "unit": u.rad, "rtol": 1e-4},
        "log.final.B.Mass": {"value": 4.25000, "unit": u.Mearth, "rtol": 1e-4},
        "log.final.B.Radius": {"value": 8.59523e07, "unit": u.m, "rtol": 1e-4},
        "log.final.B.RadGyra": {"value": 0.50000, "rtol": 1e-4},
        "log.final.B.BodyType": {"value": 0.00000, "rtol": 1e-4},
        "log.final.B.Density": {
            "value": 9.54248,
            "unit": u.kg / u.m**3,
            "rtol": 1e-4,
        },
        "log.final.B.HZLimitDryRunaway": {
            "value": 4.29453e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.B.HZLimRecVenus": {"value": 3.53836e09, "unit": u.m, "rtol": 1e-4},
        "log.final.B.HZLimRunaway": {"value": 4.62043e09, "unit": u.m, "rtol": 1e-4},
        "log.final.B.HZLimMoistGreenhouse": {
            "value": 4.68180e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.B.HZLimMaxGreenhouse": {
            "value": 7.93585e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.B.HZLimEarlyMars": {"value": 8.65866e09, "unit": u.m, "rtol": 1e-4},
        "log.final.B.Instellation": {
            "value": 10.58329,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.B.Eccentricity": {"value": 0.01800, "rtol": 1e-4},
        "log.final.B.MeanMotion": {
            "value": 1.09300e-06,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.B.OrbPeriod": {"value": 5.74856e06, "unit": u.sec, "rtol": 1e-4},
        "log.final.B.SemiMajorAxis": {"value": 5.37805e10, "unit": u.m, "rtol": 1e-4},
        "log.final.B.COPP": {"value": -0.00000, "rtol": 1e-4},
        "log.final.B.OrbAngMom": {
            "value": 8.02269e40,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.B.ArgP": {"value": 4.46827, "unit": u.rad, "rtol": 1e-4},
        "log.final.B.MeanAnomaly": {"value": 5.79807, "unit": u.rad, "rtol": 1e-4},
        "log.final.B.Inc": {"value": 0.92273, "unit": u.rad, "rtol": 1e-4},
        "log.final.B.LongA": {"value": 6.27639, "unit": u.rad, "rtol": 1e-4},
        "log.final.B.MeanLongitude": {"value": 10.25955, "unit": u.rad, "rtol": 1e-4},
        "log.final.B.LongP": {"value": 4.46148, "unit": u.rad, "rtol": 1e-4},
        "log.final.B.LXUVTot": {
            "value": -1.00000,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.B.TotOrbEnergy": {
            "value": -9.47283e34,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.B.OrbPotEnergy": {
            "value": -3.37544e29,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.B.SurfWaterMass": {"value": 0.00000, "unit": u.kg, "rtol": 1e-4},
        "log.final.B.EnvelopeMass": {"value": 0.81818, "unit": u.Mearth, "rtol": 1e-4},
        "log.final.B.OxygenMass": {"value": 0.00000, "unit": u.kg, "rtol": 1e-4},
        "log.final.B.RGLimit": {"value": 4.35523e09, "unit": u.m, "rtol": 1e-4},
        "log.final.B.XO": {"value": 0.00000, "rtol": 1e-4},
        "log.final.B.EtaO": {"value": 0.00000, "rtol": 1e-4},
        "log.final.B.PlanetRadius": {"value": 13.47616, "unit": u.Rearth, "rtol": 1e-4},
        "log.final.B.OxygenMantleMass": {"value": 0.00000, "unit": u.kg, "rtol": 1e-4},
        "log.final.B.RadXUV": {"value": -1.00000, "unit": u.m, "rtol": 1e-4},
        "log.final.B.RadSolid": {"value": -1.00000, "unit": u.m, "rtol": 1e-4},
        "log.final.B.PresXUV": {"value": 5.00000, "rtol": 1e-4},
        "log.final.B.ScaleHeight": {"value": -1.00000, "unit": u.m, "rtol": 1e-4},
        "log.final.B.ThermTemp": {"value": 400.00000, "unit": u.K, "rtol": 1e-4},
        "log.final.B.AtmGasConst": {"value": 4124.00000, "rtol": 1e-4},
        "log.final.B.PresSurf": {"value": -1.00000, "unit": u.Pa, "rtol": 1e-4},
        "log.final.B.DEnvMassDt": {
            "value": -1.49227e09,
            "unit": u.kg / u.sec,
            "rtol": 1e-4,
        },
        "log.final.B.FXUV": {"value": 10.58329, "unit": u.W / u.m**2, "rtol": 1e-4},
        "log.final.B.AtmXAbsEffH2O": {"value": 0.30000, "rtol": 1e-4},
        "log.final.B.RocheRadius": {"value": 7.78974e08, "unit": u.m, "rtol": 1e-4},
        "log.final.B.BondiRadius": {"value": 2.23590e10, "unit": u.m, "rtol": 1e-4},
        "log.final.B.HEscapeRegime": {"value": 3.00000, "rtol": 1e-4},
        "log.final.B.RRCriticalFlux": {
            "value": 0.62207,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.B.CrossoverMass": {"value": 0.00000, "unit": u.kg, "rtol": 1e-4},
        "log.final.B.WaterEscapeRegime": {"value": 8.00000, "rtol": 1e-4},
        "log.final.B.FXUVCRITDRAG": {
            "value": 0.00197,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.B.HREFFLUX": {
            "value": 2.90398e19,
            "unit": 1 / u.m**2 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.B.XO2": {"value": 0.00000, "rtol": 1e-4},
        "log.final.B.XH2O": {"value": 0.00000, "rtol": 1e-4},
        "log.final.B.HDiffFlux": {
            "value": 4.44012e15,
            "unit": 1 / u.m**2 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.B.HRefODragMod": {"value": 1.00000, "rtol": 1e-4},
        "log.final.B.KTide": {"value": 0.83516, "rtol": 1e-4},
        "log.final.B.RGDuration": {"value": 1.00000e-04, "unit": u.yr, "rtol": 1e-4},
        "log.final.B.PositionXSpiNBody": {"value": -3.60950e10, "rtol": 1e-4},
        "log.final.B.PositionYSpiNBody": {"value": -2.32119e10, "rtol": 1e-4},
        "log.final.B.PositionZSpiNBody": {"value": -3.09792e10, "rtol": 1e-4},
        "log.final.B.VelXSpiNBody": {"value": 4.40237e04, "rtol": 1e-4},
        "log.final.B.VelYSpiNBody": {"value": -2.45504e04, "rtol": 1e-4},
        "log.final.B.VelZSpiNBody": {"value": -3.20286e04, "rtol": 1e-4},
        "log.final.B.SpiNBodyInc": {"value": 0.92273, "unit": u.rad, "rtol": 1e-4},
        "log.final.B.SpiNBodyLongA": {"value": 6.27639, "unit": u.rad, "rtol": 1e-4},
        "log.final.C.Mass": {"value": 3.87300, "unit": u.Mearth, "rtol": 1e-4},
        "log.final.C.Radius": {"value": 9.65087e07, "unit": u.m, "rtol": 1e-4},
        "log.final.C.RadGyra": {"value": 0.50000, "rtol": 1e-4},
        "log.final.C.BodyType": {"value": 0.00000, "rtol": 1e-4},
        "log.final.C.Density": {
            "value": 6.14317,
            "unit": u.kg / u.m**3,
            "rtol": 1e-4,
        },
        "log.final.C.HZLimitDryRunaway": {
            "value": 4.29527e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.C.HZLimRecVenus": {"value": 3.53836e09, "unit": u.m, "rtol": 1e-4},
        "log.final.C.HZLimRunaway": {"value": 4.62043e09, "unit": u.m, "rtol": 1e-4},
        "log.final.C.HZLimMoistGreenhouse": {
            "value": 4.68180e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.C.HZLimMaxGreenhouse": {
            "value": 7.93585e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.C.HZLimEarlyMars": {"value": 8.65866e09, "unit": u.m, "rtol": 1e-4},
        "log.final.C.Instellation": {
            "value": 6.29763,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.C.Eccentricity": {"value": 0.02578, "rtol": 1e-4},
        "log.final.C.MeanMotion": {
            "value": 7.40426e-07,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.C.OrbPeriod": {"value": 8.48590e06, "unit": u.sec, "rtol": 1e-4},
        "log.final.C.SemiMajorAxis": {"value": 6.97242e10, "unit": u.m, "rtol": 1e-4},
        "log.final.C.COPP": {"value": 0.00000, "rtol": 1e-4},
        "log.final.C.OrbAngMom": {
            "value": 8.32310e40,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.C.ArgP": {"value": 1.90067, "unit": u.rad, "rtol": 1e-4},
        "log.final.C.MeanAnomaly": {"value": 5.75990, "unit": u.rad, "rtol": 1e-4},
        "log.final.C.Inc": {"value": 0.82276, "unit": u.rad, "rtol": 1e-4},
        "log.final.C.LongA": {"value": 0.06377, "unit": u.rad, "rtol": 1e-4},
        "log.final.C.MeanLongitude": {"value": 7.72433, "unit": u.rad, "rtol": 1e-4},
        "log.final.C.LongP": {"value": 1.96443, "unit": u.rad, "rtol": 1e-4},
        "log.final.C.LXUVTot": {
            "value": -1.00000,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.C.TotOrbEnergy": {
            "value": -9.47283e34,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.C.OrbPotEnergy": {"value": 0.00000, "unit": u.Joule, "rtol": 1e-4},
        "log.final.C.SurfWaterMass": {"value": 0.00000, "unit": u.kg, "rtol": 1e-4},
        "log.final.C.EnvelopeMass": {"value": 0.81818, "unit": u.Mearth, "rtol": 1e-4},
        "log.final.C.OxygenMass": {"value": 0.00000, "unit": u.kg, "rtol": 1e-4},
        "log.final.C.RGLimit": {"value": 4.36356e09, "unit": u.m, "rtol": 1e-4},
        "log.final.C.XO": {"value": 0.00000, "rtol": 1e-4},
        "log.final.C.EtaO": {"value": 0.00000, "rtol": 1e-4},
        "log.final.C.PlanetRadius": {"value": 15.13126, "unit": u.Rearth, "rtol": 1e-4},
        "log.final.C.OxygenMantleMass": {"value": 0.00000, "unit": u.kg, "rtol": 1e-4},
        "log.final.C.RadXUV": {"value": -1.00000, "unit": u.m, "rtol": 1e-4},
        "log.final.C.RadSolid": {"value": -1.00000, "unit": u.m, "rtol": 1e-4},
        "log.final.C.PresXUV": {"value": 5.00000, "rtol": 1e-4},
        "log.final.C.ScaleHeight": {"value": -1.00000, "unit": u.m, "rtol": 1e-4},
        "log.final.C.ThermTemp": {"value": 400.00000, "unit": u.K, "rtol": 1e-4},
        "log.final.C.AtmGasConst": {"value": 4124.00000, "rtol": 1e-4},
        "log.final.C.PresSurf": {"value": -1.00000, "unit": u.Pa, "rtol": 1e-4},
        "log.final.C.DEnvMassDt": {
            "value": -1.35108e09,
            "unit": u.kg / u.sec,
            "rtol": 1e-4,
        },
        "log.final.C.FXUV": {"value": 6.29763, "unit": u.W / u.m**2, "rtol": 1e-4},
        "log.final.C.AtmXAbsEffH2O": {"value": 0.30000, "rtol": 1e-4},
        "log.final.C.RocheRadius": {"value": 9.79117e08, "unit": u.m, "rtol": 1e-4},
        "log.final.C.BondiRadius": {"value": 1.78950e10, "unit": u.m, "rtol": 1e-4},
        "log.final.C.HEscapeRegime": {"value": 3.00000, "rtol": 1e-4},
        "log.final.C.RRCriticalFlux": {
            "value": 0.38037,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.C.CrossoverMass": {"value": 0.00000, "unit": u.kg, "rtol": 1e-4},
        "log.final.C.WaterEscapeRegime": {"value": 8.00000, "rtol": 1e-4},
        "log.final.C.FXUVCRITDRAG": {
            "value": 0.00115,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.C.HREFFLUX": {
            "value": 2.08550e19,
            "unit": 1 / u.m**2 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.C.XO2": {"value": 0.00000, "rtol": 1e-4},
        "log.final.C.XH2O": {"value": 0.00000, "rtol": 1e-4},
        "log.final.C.HDiffFlux": {
            "value": 3.20949e15,
            "unit": 1 / u.m**2 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.C.HRefODragMod": {"value": 1.00000, "rtol": 1e-4},
        "log.final.C.KTide": {"value": 0.85263, "rtol": 1e-4},
        "log.final.C.RGDuration": {"value": 1.00000e-04, "unit": u.yr, "rtol": 1e-4},
        "log.final.C.PositionXSpiNBody": {"value": 1.19594e10, "rtol": 1e-4},
        "log.final.C.PositionYSpiNBody": {"value": 4.61140e10, "rtol": 1e-4},
        "log.final.C.PositionZSpiNBody": {"value": 4.87732e10, "rtol": 1e-4},
        "log.final.C.VelXSpiNBody": {"value": -5.20235e04, "rtol": 1e-4},
        "log.final.C.VelYSpiNBody": {"value": 4062.96629, "rtol": 1e-4},
        "log.final.C.VelZSpiNBody": {"value": 7942.27545, "rtol": 1e-4},
        "log.final.C.SpiNBodyInc": {"value": 0.82276, "unit": u.rad, "rtol": 1e-4},
        "log.final.C.SpiNBodyLongA": {"value": 0.06377, "unit": u.rad, "rtol": 1e-4},
    }
)
class Test_NBodyAtmEsc(Benchmark):
    pass
