#!/usr/bin/env python3
"""Re-run the Trappist-1e block from the source notebook (Combined for
Paper, pages 22-26) verbatim, including the plot code, to check whether
the published page-27 plot was actually generated by this code or by
something different. If our regenerated plot disagrees with the
published one, the discrepancy is in the student's plotting routine,
not the model.

Variable names match the notebook letter-for-letter so any reader
can compare lines side by side."""

import os
import sys

import matplotlib.pyplot as plt
import numpy as np
from astropy import units as u
from astropy.constants import G, R_earth, M_earth, k_B, M_sun

THIS_DIR = os.path.dirname(os.path.abspath(__file__))

# --- Constants for TRAPPIST-1e (notebook page 22) ---
m_H_TE = 3.34e-27 * u.kg
magnetic_p_TE = 4 * np.pi * 1e-7 * (u.H / u.m)
T_exo_H_TE = 900 * u.K
R_EE_TE = 0.920 * R_earth.to(u.m)
ree_exo_TE = R_EE_TE + 396000 * u.m
M_EE_TE = 0.692 * M_earth.to(u.kg)
ne_sw_TE = 5.79e3 * (1 / u.cm ** 3)
ve_sw_TE = 604000 * u.m / u.s
prot_mass_TE = 1.67e-27 * u.kg
Omega_pc_E_TE = 0.63
r_exo_E_TE = 6_871_000 * u.m
re_IMB_TE = 7_647_000 * u.m
formfact_o_TE = 1.16
Mag_Earth_TE = 8e22 * (u.A * u.m ** 2)
mass_TE = 1.67e-27 * u.kg
magnetic_moments_TE = np.logspace(17, 27, 500) * (u.A * u.m ** 2)
magnetic_m_values_earth_units_TE = magnetic_moments_TE / Mag_Earth_TE
earth_atmosphere_in_kg_TE = 1e-6 * M_earth
seconds_per_gyr_TE = 1e9 * 365.25 * 24 * 3600 * u.s

# --- Pickup escape (page 22-23) ---
Q0_pu_H_TE = 5e26 * (1 / u.s)
he_H_TE = (k_B * T_exo_H_TE * ree_exo_TE ** 2) / (G * M_EE_TE * m_H_TE)

PU_escape_TE = []
for M in magnetic_moments_TE:
    R_MP = ((magnetic_p_TE * M ** 2) /
            (8 * np.pi ** 2 * ne_sw_TE * ve_sw_TE ** 2 * prot_mass_TE)) ** (1 / 6)
    if R_MP <= ree_exo_TE:
        Q_pu = Q0_pu_H_TE
    else:
        num = 2 * he_H_TE ** 3 + 2 * he_H_TE ** 2 * R_MP + he_H_TE * R_MP ** 2
        den = (2 * he_H_TE ** 3 + 2 * he_H_TE ** 2 * ree_exo_TE +
               he_H_TE * ree_exo_TE ** 2)
        exp_term = np.exp((ree_exo_TE - R_MP) / he_H_TE)
        Q_pu = Q0_pu_H_TE * (num / den) * exp_term
    mass_loss_rate = Q_pu * mass_TE
    atmos_loss = (mass_loss_rate / earth_atmosphere_in_kg_TE) * seconds_per_gyr_TE
    PU_escape_TE.append(atmos_loss.value)
PU_escape_TE = u.Quantity(PU_escape_TE)

# --- Cross-field ion loss (page 23) ---
Q0_cf_H_TE = 7.7e25 * (1 / u.s)
CF_escape_TE = []
for M in magnetic_moments_TE:
    R_MP = ((magnetic_p_TE * M ** 2) /
            (8 * np.pi ** 2 * ne_sw_TE * ve_sw_TE ** 2 * prot_mass_TE)) ** (1 / 6)
    if R_MP >= re_IMB_TE:
        temp = 1 - (ree_exo_TE / R_MP)
        Omega_pc = 4 * np.pi * (1 - np.sqrt(temp)) if temp >= 0 else 0
    else:
        Omega_pc = 0
    Q_cf = Q0_cf_H_TE * ((1 - (Omega_pc / (4 * np.pi))) /
                         (1 - (Omega_pc_E_TE / (4 * np.pi))))
    mass_loss_rate = Q_cf * mass_TE
    atmos_loss = (mass_loss_rate / earth_atmosphere_in_kg_TE) * seconds_per_gyr_TE
    CF_escape_TE.append(atmos_loss.value)
CF_escape_TE = u.Quantity(CF_escape_TE)

# --- Polar cap loss (page 23-24) ---
Q0_pc_H_TE = 7.8e25 * (1 / u.s)
PC_escape_TE = []
for M in magnetic_moments_TE:
    R_MP = ((magnetic_p_TE * formfact_o_TE ** 2 * M ** 2) /
            (8 * np.pi ** 2 * ne_sw_TE * ve_sw_TE ** 2 * prot_mass_TE)) ** (1 / 6)
    if R_MP > re_IMB_TE:
        temp = 1 - (r_exo_E_TE / R_MP)
        Omega_pc = 4 * np.pi * (1 - np.sqrt(temp)) if temp >= 0 else 0
    else:
        Omega_pc = 0
    Q_pc = Q0_pc_H_TE * (Omega_pc / Omega_pc_E_TE) * ((ree_exo_TE / r_exo_E_TE) ** 2)
    mass_loss_rate = Q_pc * mass_TE
    atmos_loss = (mass_loss_rate / earth_atmosphere_in_kg_TE) * seconds_per_gyr_TE
    PC_escape_TE.append(atmos_loss.value)
PC_escape_TE = u.Quantity(PC_escape_TE)

# --- Cusp escape (page 24) ---
Q0_cu_H_TE = 5e24 * (1 / u.s)
Qmax_cu_H_TE = 5e25 * (1 / u.s)
nsw_E = (1e7) * (1 / u.m ** 3)
vsw_E = (604000) * (u.m / u.s)
r_c_E = ((magnetic_p_TE * Mag_Earth_TE ** 2) /
         (8 * np.pi ** 2 * nsw_E * vsw_E ** 2 * prot_mass_TE)) ** (1 / 6)
CU_escape_TE = []
for M in magnetic_moments_TE:
    R_MP_TE = ((magnetic_p_TE * M ** 2) /
               (8 * np.pi ** 2 * ne_sw_TE * ve_sw_TE ** 2 * prot_mass_TE)) ** (1 / 6)
    r_c_E_TE = R_MP_TE
    if R_MP_TE > re_IMB_TE:
        temp_TE = 1 - (r_exo_E_TE / R_MP_TE)
        Omega_pc_TE = 4 * np.pi * (1 - np.sqrt(temp_TE)) if temp_TE >= 0 else 0
    else:
        Omega_pc_TE = 0
    Q_cu_TE = (min(Q0_cu_H_TE * (r_c_E_TE / r_c_E) ** 2, Qmax_cu_H_TE) *
               (Omega_pc_TE / Omega_pc_E_TE) *
               (ree_exo_TE / r_exo_E_TE) ** 2)
    mass_loss_rate_TE = Q_cu_TE * mass_TE
    atmos_loss_TE = (mass_loss_rate_TE / earth_atmosphere_in_kg_TE) * seconds_per_gyr_TE
    CU_escape_TE.append(atmos_loss_TE.value)
CU_escape_TE = u.Quantity(CU_escape_TE)

# --- Driscoll Ion Pickup (page 25) ---
time_TE = 10 * u.s
mass_water_TE = 1e21 * u.kg
sigma_coll_TE = 1e-17 * u.m ** 2
energy_eff_TE = 1 / (10.6e44)
MPU_escape_TE = []
for M in magnetic_moments_TE:
    r_mp = ((magnetic_p_TE * M ** 2) /
            (8 * np.pi ** 2 * ne_sw_TE * ve_sw_TE ** 2 * prot_mass_TE)) ** (1 / 6)
    h_exo = (k_B * T_exo_H_TE * ree_exo_TE ** 2) / (G * M_EE_TE * m_H_TE)
    n_exo = 1 / (h_exo * sigma_coll_TE)
    n_L = n_exo * np.exp((-ree_exo_TE / h_exo) * (1 - (ree_exo_TE / r_mp)))
    surface_a = 4 * np.pi * r_mp ** 2
    f_lm = (((energy_eff_TE * h_exo * surface_a *
              (n_L - ne_sw_TE)) / time_TE) * mass_water_TE)
    mass_loss_rate = f_lm * mass_TE
    atmos_loss = (mass_loss_rate / earth_atmosphere_in_kg_TE) * seconds_per_gyr_TE
    MPU_escape_TE.append(atmos_loss.value)
MPU_escape_TE = u.Quantity(MPU_escape_TE)

# --- Energy-limited (page 25) ---
a_TE = (52.855 * 84e6) * u.m
M_star_TE = 0.09 * M_sun
epsilon_TE = 0.1
L_bol_TE = 3.828e26 * u.W
L_xuv_TE = 3.4e-4 * L_bol_TE
F_xuv_TE = L_xuv_TE / (4 * np.pi * a_TE ** 2)
rho_TE = M_EE_TE / ((4 / 3) * np.pi * R_EE_TE ** 3)
r_roche_TE = a_TE * (M_EE_TE / (2 * M_star_TE)) ** (1 / 3)
K_TE = 1 - (3 / 2) * (R_EE_TE / r_roche_TE) + (1 / 2) * (R_EE_TE / r_roche_TE) ** 3
mdot_TE = epsilon_TE * (R_EE_TE / R_EE_TE) ** 2 * (3 * F_xuv_TE) / (4 * G * rho_TE * K_TE)
mdot_TE = mdot_TE.to(u.kg / u.s)
mdot_earth_per_gyr_TE = (mdot_TE * seconds_per_gyr_TE / M_earth)
mdot_array_TE = u.Quantity(np.full(magnetic_moments_TE.shape,
                                   mdot_earth_per_gyr_TE.value),
                           unit=mdot_earth_per_gyr_TE.unit)

# --- Total (notebook line) ---
total_escape_TE = (PU_escape_TE.value + CU_escape_TE.value +
                   PC_escape_TE.value + CF_escape_TE.value)


def fnPrintAtSelectedM():
    """Print numerical values at M={0.083 (just past threshold), 0.1, 1.0}."""
    daM = magnetic_m_values_earth_units_TE.value
    iSelected = [np.argmin(np.abs(daM - target))
                 for target in [0.083, 0.1, 1.0]]
    print(f"{'M_E':>10}  {'Pickup':>12}  {'CrossF':>12}  {'PolarC':>12}  "
          f"{'Cusp':>12}  {'Driscl':>12}  {'CF/Cusp':>10}")
    for i in iSelected:
        m_at_i = daM[i]
        cusp_at_i = CU_escape_TE.value[i]
        cf_at_i = CF_escape_TE.value[i]
        ratio = cf_at_i / cusp_at_i if cusp_at_i > 0 else float("inf")
        print(f"{m_at_i:>10.4f}  {PU_escape_TE.value[i]:>12.4e}  "
              f"{cf_at_i:>12.4e}  {PC_escape_TE.value[i]:>12.4e}  "
              f"{cusp_at_i:>12.4e}  {MPU_escape_TE.value[i]:>12.4e}  "
              f"{ratio:>10.2f}")


def fnPlotNotebookStyle(sOutputPath):
    """Reproduce the notebook page-27 plot style exactly."""
    fig = plt.figure(figsize=(10, 7))
    plt.loglog(magnetic_m_values_earth_units_TE.value, mdot_array_TE.value,
               label='Energy-Limited Escape', color='red', linewidth=3)
    plt.loglog(magnetic_m_values_earth_units_TE.value, MPU_escape_TE.value,
               label='Driscoll Ion Pickup', color='gold')
    plt.loglog(magnetic_m_values_earth_units_TE.value, PU_escape_TE.value,
               '--', label='Pickup H Escape', color='orange')
    plt.loglog(magnetic_m_values_earth_units_TE.value, CF_escape_TE.value,
               '-', label='Cross-field H Escape', color='blue')
    plt.loglog(magnetic_m_values_earth_units_TE.value, PC_escape_TE.value,
               label='Polar Cap H Escape', color='purple')
    plt.loglog(magnetic_m_values_earth_units_TE.value, CU_escape_TE.value,
               '--', label='Cusp H Escape', color='hotpink')
    plt.loglog(magnetic_m_values_earth_units_TE.value, total_escape_TE,
               linewidth=2.5, color='black', label='Total H Escape')
    plt.xlabel('Magnetic Dipole Moment [Earth Units]')
    plt.ylabel('Escape Rate [Earth atm / Gyr]')
    plt.title('TRAPPIST-1e regenerated from notebook code (verbatim)')
    plt.legend(loc='lower left', fontsize=10)
    plt.ylim(1e-35, 1e5)
    plt.xlim(1e-4, 1e2)
    plt.grid(alpha=0.3, which="both")
    plt.tight_layout()
    plt.savefig(sOutputPath, dpi=150)
    print(f"Wrote {sOutputPath}")


if __name__ == "__main__":
    print("Notebook code, run verbatim, at selected M:\n")
    fnPrintAtSelectedM()
    sOutputPath = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        THIS_DIR, "T1e_NotebookRegenerated.png")
    fnPlotNotebookStyle(sOutputPath)
