import astropy.units as u
import pytest
from benchmark import Benchmark, benchmark


@benchmark(
    {
        "log.initial.system.Age": {"value": 3.155760e13, "unit": u.sec},
        "log.initial.system.Time": {"value": 0.000000, "unit": u.sec},
        "log.initial.system.TotAngMom": {
            "value": 8.686138e39,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.system.TotEnergy": {"value": -1.657581e39, "unit": u.erg},
        "log.initial.system.PotEnergy": {"value": -1.657567e39, "unit": u.Joule},
        "log.initial.system.KinEnergy": {"value": 1.389414e33, "unit": u.Joule},
        "log.initial.system.DeltaTime": {"value": 0.000000, "unit": u.sec},
        "log.initial.TGstar.Mass": {"value": 1.590733e29, "unit": u.kg},
        "log.initial.TGstar.Obliquity": {"value": 0.000000, "unit": u.rad},
        "log.initial.TGstar.PrecA": {"value": 0.000000, "unit": u.rad},
        "log.initial.TGstar.Xobl": {"value": 0.000000},
        "log.initial.TGstar.Yobl": {"value": 0.000000},
        "log.initial.TGstar.Zobl": {"value": 1.000000},
        "log.initial.TGstar.Radius": {"value": 95.849006, "unit": u.Rearth},
        "log.initial.TGstar.RadGyra": {"value": 0.445942},
        "log.initial.TGstar.RotAngMom": {
            "value": 5.731743e39,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.TGstar.RotKinEnergy": {"value": 1.389414e33, "unit": u.Joule},
        "log.initial.TGstar.RotVel": {"value": 296.383353, "unit": u.m / u.sec},
        "log.initial.TGstar.BodyType": {"value": 0.000000},
        "log.initial.TGstar.RotRate": {"value": 4.848137e-07, "unit": 1 / u.sec},
        "log.initial.TGstar.RotPer": {"value": 150.000000, "unit": u.day},
        "log.initial.TGstar.Density": {"value": 166.215610, "unit": u.kg / u.m**3},
        "log.initial.TGstar.SurfEnFluxTotal": {
            "value": 0.000237,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.TGstar.TidalQ": {"value": 1.000000e06},
        "log.initial.TGstar.ImK2": {"value": -5.000000e-07},
        "log.initial.TGstar.K2": {"value": 0.500000},
        "log.initial.TGstar.K2Man": {"value": 0.010000},
        "log.initial.TGstar.Imk2Man": {"value": 0.000000},
        "log.initial.TGstar.TidalQMantle": {"value": 100.000000},
        "log.initial.TGstar.HEcc": {"value": 0.000000},
        "log.initial.TGstar.HZLimitDryRunaway": {"value": 3.002086e10, "unit": u.m},
        "log.initial.TGstar.HZLimRecVenus": {"value": 2.704556e10, "unit": u.m},
        "log.initial.TGstar.HZLimRunaway": {"value": 3.557903e10, "unit": u.m},
        "log.initial.TGstar.HZLimMoistGreenhouse": {"value": 3.578576e10, "unit": u.m},
        "log.initial.TGstar.HZLimMaxGreenhouse": {"value": 6.881980e10, "unit": u.m},
        "log.initial.TGstar.HZLimEarlyMars": {"value": 7.505521e10, "unit": u.m},
        "log.initial.TGstar.Instellation": {
            "value": -1.000000,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.TGstar.KEcc": {"value": 0.000000},
        "log.initial.TGstar.Eccentricity": {"value": -1.000000},
        "log.initial.TGstar.OrbEnergy": {"value": 0.000000, "unit": u.Joule},
        "log.initial.TGstar.MeanMotion": {"value": -1.000000, "unit": 1 / u.sec},
        "log.initial.TGstar.OrbPeriod": {"value": -1.000000, "unit": u.sec},
        "log.initial.TGstar.SemiMajorAxis": {"value": -1.000000, "unit": u.m},
        "log.initial.TGstar.CriticalSemiMajorAxis": {"value": -1.000000, "unit": u.m},
        "log.initial.TGstar.COPP": {"value": 0.000000},
        "log.initial.TGstar.OrbAngMom": {
            "value": 0.000000,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.TGstar.LongP": {"value": 0.000000, "unit": u.rad},
        "log.initial.TGstar.LXUVTot": {"value": 1.880028e22, "unit": u.kg / u.sec**3},
        "log.initial.TGstar.TotOrbEnergy": {"value": -1.426284e34, "unit": u.Joule},
        "log.initial.TGstar.OrbPotEnergy": {"value": -1.000000, "unit": u.Joule},
        "log.initial.TGstar.LostEnergy": {"value": 5.562685e-309, "unit": u.Joule},
        "log.initial.TGstar.LostAngMom": {
            "value": 5.562685e-309,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.TGstar.LockTime": {"value": -1.000000, "unit": u.sec},
        "log.initial.TGstar.BodyDsemiDtEqtide": {"value": -1.000000},
        "log.initial.TGstar.BodyDeccDt": {"value": -1.000000},
        "log.initial.TGstar.DOblDtEqtide": {"value": 0.000000, "unit": u.rad / u.sec},
        "log.initial.TGstar.DRotPerDtEqtide": {"value": -1.646667e-13},
        "log.initial.TGstar.DRotRateDtEqtide": {
            "value": 6.159929e-27,
            "unit": 1 / u.sec**2,
        },
        "log.initial.TGstar.EqRotRateDiscrete": {
            "value": 1.407734e-05,
            "unit": 1 / u.sec,
        },
        "log.initial.TGstar.EqRotPerDiscrete": {"value": 4.463334e05, "unit": u.sec},
        "log.initial.TGstar.EqRotRateCont": {"value": 1.750094e-05, "unit": 1 / u.sec},
        "log.initial.TGstar.EqRotPerCont": {"value": 3.590198e05, "unit": u.sec},
        "log.initial.TGstar.EqRotPer": {"value": 4.463334e05, "unit": u.sec},
        "log.initial.TGstar.EqTidePower": {"value": 0.000000, "unit": 1 / u.sec},
        "log.initial.TGstar.GammaRot": {"value": -1.000000, "unit": u.sec},
        "log.initial.TGstar.GammaOrb": {"value": -1.000000, "unit": u.sec},
        "log.initial.TGstar.OceanK2": {"value": 0.010000},
        "log.initial.TGstar.EnvTidalQ": {"value": -1.000000},
        "log.initial.TGstar.OceanTidalQ": {"value": -1.000000},
        "log.initial.TGstar.TideLock": {"value": 0.000000},
        "log.initial.TGstar.RotTimeEqtide": {"value": 5.903564e-27, "unit": u.sec},
        "log.initial.TGstar.EnvK2": {"value": 0.010000},
        "log.initial.TGstar.OblTimeEqtide": {"value": -1.000000},
        "log.initial.TGstar.PowerEqtide": {"value": 1.111348e15, "unit": u.W},
        "log.initial.TGstar.SurfEnFluxEqtide": {
            "value": 0.000237,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.TGstar.Luminosity": {"value": 0.048883, "unit": u.LSUN},
        "log.initial.TGstar.LXUVStellar": {"value": 1.880028e22, "unit": u.W},
        "log.initial.TGstar.Temperature": {"value": 2897.423645, "unit": u.K},
        "log.initial.TGstar.LXUVFrac": {"value": 0.001000},
        "log.initial.TGstar.RossbyNumber": {"value": 2.105193},
        "log.initial.TGstar.DRotPerDtStellar": {"value": -2.680275e-08},
        "log.initial.TGb.Mass": {"value": 6.270795e24, "unit": u.kg},
        "log.initial.TGb.Obliquity": {"value": 0.523599, "unit": u.rad},
        "log.initial.TGb.PrecA": {"value": 0.000000, "unit": u.rad},
        "log.initial.TGb.Xobl": {"value": 0.500000},
        "log.initial.TGb.Yobl": {"value": 0.000000},
        "log.initial.TGb.Zobl": {"value": 0.866025},
        "log.initial.TGb.Radius": {"value": 7.653720e06, "unit": u.m},
        "log.initial.TGb.RadGyra": {"value": 0.400000},
        "log.initial.TGb.RotAngMom": {
            "value": 4.274190e33,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.TGb.RotKinEnergy": {"value": 1.554140e29, "unit": u.Joule},
        "log.initial.TGb.RotVel": {"value": 556.594225, "unit": u.m / u.sec},
        "log.initial.TGb.BodyType": {"value": 0.000000},
        "log.initial.TGb.RotRate": {"value": 7.272205e-05, "unit": 1 / u.sec},
        "log.initial.TGb.RotPer": {"value": 1.000000, "unit": u.day},
        "log.initial.TGb.Density": {"value": 3338.999118, "unit": u.kg / u.m**3},
        "log.initial.TGb.SurfEnFluxTotal": {
            "value": 6424.692266,
            "unit": u.W / u.m**2,
        },
        "log.initial.TGb.TidalQ": {"value": 100.000000},
        "log.initial.TGb.ImK2": {"value": -0.003000},
        "log.initial.TGb.K2": {"value": 0.300000},
        "log.initial.TGb.K2Man": {"value": 0.010000},
        "log.initial.TGb.Imk2Man": {"value": 0.000000},
        "log.initial.TGb.TidalQMantle": {"value": 100.000000},
        "log.initial.TGb.HEcc": {"value": 0.155899},
        "log.initial.TGb.HZLimitDryRunaway": {"value": 3.041267e10, "unit": u.m},
        "log.initial.TGb.HZLimRecVenus": {"value": 2.704556e10, "unit": u.m},
        "log.initial.TGb.HZLimRunaway": {"value": 3.557903e10, "unit": u.m},
        "log.initial.TGb.HZLimMoistGreenhouse": {"value": 3.578576e10, "unit": u.m},
        "log.initial.TGb.HZLimMaxGreenhouse": {"value": 6.881980e10, "unit": u.m},
        "log.initial.TGb.HZLimEarlyMars": {"value": 7.505521e10, "unit": u.m},
        "log.initial.TGb.Instellation": {
            "value": 1.066434e05,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.TGb.KEcc": {"value": 0.035992},
        "log.initial.TGb.Eccentricity": {"value": 0.160000},
        "log.initial.TGb.OrbEnergy": {"value": -8.830155e33, "unit": u.Joule},
        "log.initial.TGb.MeanMotion": {"value": 1.407734e-05, "unit": 1 / u.sec},
        "log.initial.TGb.OrbPeriod": {"value": 4.463334e05, "unit": u.sec},
        "log.initial.TGb.SemiMajorAxis": {"value": 3.769866e09, "unit": u.m},
        "log.initial.TGb.CriticalSemiMajorAxis": {"value": -1.000000, "unit": u.m},
        "log.initial.TGb.COPP": {"value": 0.077950},
        "log.initial.TGb.OrbAngMom": {
            "value": 1.238359e39,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.TGb.ArgP": {"value": 0.680678, "unit": u.rad},
        "log.initial.TGb.Inc": {"value": 0.174533, "unit": u.rad},
        "log.initial.TGb.LongA": {"value": 0.663225, "unit": u.rad},
        "log.initial.TGb.MeanLongitude": {"value": 1.343904, "unit": u.rad},
        "log.initial.TGb.LongP": {"value": 1.343904, "unit": u.rad},
        "log.initial.TGb.TotOrbEnergy": {"value": -1.426284e34, "unit": u.Joule},
        "log.initial.TGb.OrbPotEnergy": {"value": -1.766031e34, "unit": u.Joule},
        "log.initial.TGb.LostEnergy": {"value": 5.562685e-309, "unit": u.Joule},
        "log.initial.TGb.TidalRadius": {"value": 7.653720e06, "unit": u.m},
        "log.initial.TGb.DsemiDtEqtide": {"value": 5.538532e-07, "unit": u.m / u.sec},
        "log.initial.TGb.DeccDtEqtide": {"value": 4.207972e-17, "unit": 1 / u.sec},
        "log.initial.TGb.DMeanMotionDtEqtide": {
            "value": -3.102276e-21,
            "unit": 1 / u.sec**2,
        },
        "log.initial.TGb.DOrbPerDtEqtide": {"value": 9.836020e-11},
        "log.initial.TGb.EccTimeEqtide": {"value": 3.802307e15, "unit": u.sec},
        "log.initial.TGb.SemiTimeEqtide": {"value": 6.806616e15, "unit": u.sec},
        "log.initial.TGb.DHEccDtEqtide": {"value": 4.100122e-17, "unit": 1 / u.sec},
        "log.initial.TGb.DKEccDtEqtide": {"value": 9.465877e-18, "unit": 1 / u.sec},
        "log.initial.TGb.DXoblDtEqtide": {"value": 3.522361e-12, "unit": 1 / u.sec},
        "log.initial.TGb.DYoblDtEqtide": {"value": 0.000000, "unit": 1 / u.sec},
        "log.initial.TGb.DZoblDtEqtide": {"value": -2.033636e-12, "unit": 1 / u.sec},
        "log.initial.TGb.LockTime": {"value": -1.000000, "unit": u.sec},
        "log.initial.TGb.BodyDsemiDtEqtide": {"value": -1.000000},
        "log.initial.TGb.BodyDeccDt": {"value": -1.000000},
        "log.initial.TGb.DOblDtEqtide": {"value": 4.067272e-12, "unit": u.rad / u.sec},
        "log.initial.TGb.DRotPerDtEqtide": {"value": 1.675539e-06},
        "log.initial.TGb.DRotRateDtEqtide": {
            "value": -1.410286e-15,
            "unit": 1 / u.sec**2,
        },
        "log.initial.TGb.EqRotRateDiscrete": {"value": 1.407734e-05, "unit": 1 / u.sec},
        "log.initial.TGb.EqRotPerDiscrete": {"value": 4.463334e05, "unit": u.sec},
        "log.initial.TGb.EqRotRateCont": {"value": 1.750094e-05, "unit": 1 / u.sec},
        "log.initial.TGb.EqRotPerCont": {"value": 3.590198e05, "unit": u.sec},
        "log.initial.TGb.EqRotPer": {"value": 4.463334e05, "unit": u.sec},
        "log.initial.TGb.EqTidePower": {"value": 0.000000, "unit": 1 / u.sec},
        "log.initial.TGb.GammaRot": {"value": -1.000000, "unit": u.sec},
        "log.initial.TGb.GammaOrb": {"value": -1.000000, "unit": u.sec},
        "log.initial.TGb.OceanK2": {"value": 0.010000},
        "log.initial.TGb.EnvTidalQ": {"value": -1.000000},
        "log.initial.TGb.OceanTidalQ": {"value": -1.000000},
        "log.initial.TGb.TideLock": {"value": 0.000000},
        "log.initial.TGb.RotTimeEqtide": {"value": 5.156548e10, "unit": u.sec},
        "log.initial.TGb.EnvK2": {"value": 0.010000},
        "log.initial.TGb.OblTimeEqtide": {"value": -1.000000},
        "log.initial.TGb.PowerEqtide": {"value": 4.729414e18, "unit": u.W},
        "log.initial.TGb.SurfEnFluxEqtide": {
            "value": 6424.692266,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.TGb.Sinc": {"value": 0.087156},
        "log.initial.TGb.Pinc": {"value": 0.053658},
        "log.initial.TGb.Qinc": {"value": 0.068680},
        "log.initial.TGb.DIncDtDistOrb": {
            "value": -1.444615e-12,
            "unit": u.rad / u.sec,
        },
        "log.initial.TGb.DSincDtDistOrb": {"value": -7.195591e-13, "unit": 1 / u.sec},
        "log.initial.TGb.DLongADtDistOrb": {
            "value": -3.527505e-10,
            "unit": u.rad / u.sec,
        },
        "log.initial.TGb.DLongPDtDistOrb": {
            "value": 2.385502e-10,
            "unit": u.rad / u.sec,
        },
        "log.initial.TGb.DHeccDtDistOrb": {"value": 6.306456e-12, "unit": 1 / u.sec},
        "log.initial.TGb.DKeccDtDistOrb": {"value": -3.771605e-11, "unit": 1 / u.sec},
        "log.initial.TGb.DPincDtDistOrb": {"value": -2.466979e-11, "unit": 1 / u.sec},
        "log.initial.TGb.DQincDtDistOrb": {"value": 1.836102e-11, "unit": 1 / u.sec},
        "log.initial.TGb.CassiniOne": {"value": 0.748131},
        "log.initial.TGb.CassiniTwo": {"value": 0.663551},
        "log.initial.TGb.DOblDtDistRot": {"value": 3.657365e-11, "unit": u.rad},
        "log.initial.TGb.DPrecADtDistRot": {
            "value": 1.996027e-08,
            "unit": u.rad / u.sec,
        },
        "log.initial.TGb.DXoblDtDistRot": {"value": 3.167371e-11, "unit": 1 / u.sec},
        "log.initial.TGb.DYoblDtDistRot": {"value": 9.980137e-09, "unit": 1 / u.sec},
        "log.initial.TGb.DZoblDtDistRot": {"value": -1.828682e-11, "unit": 1 / u.sec},
        "log.initial.TGb.OblTimeDistRot": {"value": 8.589771e10, "unit": u.rad},
        "log.initial.TGb.PrecATimeDistRot": {"value": 3.147845e08, "unit": u.sec},
        "log.initial.TGb.XoblTimeDistRot": {"value": 3.157193e10, "unit": 1 / u.sec},
        "log.initial.TGb.YoblTimeDistRot": {"value": 1.001990e08, "unit": 1 / u.sec},
        "log.initial.TGb.ZoblTimeDistRot": {"value": 5.468418e10, "unit": 1 / u.sec},
        "log.initial.TGb.DynEllip": {"value": 0.005399},
        "log.initial.TGb.PrecFNat": {"value": 1.986977e-08, "unit": u.rad / u.sec},
        "log.initial.TGc.Mass": {"value": 6.629126e24, "unit": u.kg},
        "log.initial.TGc.Obliquity": {"value": 0.000000, "unit": u.rad},
        "log.initial.TGc.PrecA": {"value": 0.000000, "unit": u.rad},
        "log.initial.TGc.Xobl": {"value": 0.000000},
        "log.initial.TGc.Yobl": {"value": 0.000000},
        "log.initial.TGc.Zobl": {"value": 1.000000},
        "log.initial.TGc.Radius": {"value": 9.567150e06, "unit": u.m},
        "log.initial.TGc.RadGyra": {"value": 0.400000},
        "log.initial.TGc.RotAngMom": {
            "value": 7.060047e33,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.TGc.RotKinEnergy": {"value": 2.567105e29, "unit": u.Joule},
        "log.initial.TGc.RotVel": {"value": 695.742781, "unit": u.m / u.sec},
        "log.initial.TGc.BodyType": {"value": 0.000000},
        "log.initial.TGc.RotRate": {"value": 7.272205e-05, "unit": 1 / u.sec},
        "log.initial.TGc.RotPer": {"value": 1.000000, "unit": u.day},
        "log.initial.TGc.Density": {"value": 1807.257123, "unit": u.kg / u.m**3},
        "log.initial.TGc.SurfEnFluxTotal": {
            "value": 4683.535069,
            "unit": u.W / u.m**2,
        },
        "log.initial.TGc.TidalQ": {"value": 12.000000},
        "log.initial.TGc.ImK2": {"value": -0.025000},
        "log.initial.TGc.K2": {"value": 0.300000},
        "log.initial.TGc.K2Man": {"value": 0.010000},
        "log.initial.TGc.Imk2Man": {"value": 0.000000},
        "log.initial.TGc.TidalQMantle": {"value": 100.000000},
        "log.initial.TGc.HEcc": {"value": -0.118903},
        "log.initial.TGc.HZLimitDryRunaway": {"value": 3.041267e10, "unit": u.m},
        "log.initial.TGc.HZLimRecVenus": {"value": 2.704556e10, "unit": u.m},
        "log.initial.TGc.HZLimRunaway": {"value": 3.557903e10, "unit": u.m},
        "log.initial.TGc.HZLimMoistGreenhouse": {"value": 3.578576e10, "unit": u.m},
        "log.initial.TGc.HZLimMaxGreenhouse": {"value": 6.881980e10, "unit": u.m},
        "log.initial.TGc.HZLimEarlyMars": {"value": 7.505521e10, "unit": u.m},
        "log.initial.TGc.Instellation": {
            "value": 3.612095e04,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.TGc.KEcc": {"value": 0.107061},
        "log.initial.TGc.Eccentricity": {"value": 0.160000},
        "log.initial.TGc.OrbEnergy": {"value": -5.432687e33, "unit": u.Joule},
        "log.initial.TGc.MeanMotion": {"value": 6.250142e-06, "unit": 1 / u.sec},
        "log.initial.TGc.OrbPeriod": {"value": 1.005287e06, "unit": u.sec},
        "log.initial.TGc.SemiMajorAxis": {"value": 6.477588e09, "unit": u.m},
        "log.initial.TGc.CriticalSemiMajorAxis": {"value": -1.000000, "unit": u.m},
        "log.initial.TGc.COPP": {"value": -0.000000},
        "log.initial.TGc.OrbAngMom": {
            "value": 1.716024e39,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.TGc.ArgP": {"value": 0.994838, "unit": u.rad},
        "log.initial.TGc.Inc": {"value": 0.069813, "unit": u.rad},
        "log.initial.TGc.LongA": {"value": 4.450590, "unit": u.rad},
        "log.initial.TGc.MeanLongitude": {"value": -0.837758, "unit": u.rad},
        "log.initial.TGc.LongP": {"value": 5.445427, "unit": u.rad},
        "log.initial.TGc.TotOrbEnergy": {"value": -1.426284e34, "unit": u.Joule},
        "log.initial.TGc.OrbPotEnergy": {"value": -1.086537e34, "unit": u.Joule},
        "log.initial.TGc.LostEnergy": {"value": 5.562685e-309, "unit": u.Joule},
        "log.initial.TGc.TidalRadius": {"value": 9.567150e06, "unit": u.m},
        "log.initial.TGc.DsemiDtEqtide": {"value": 6.792189e-07, "unit": u.m / u.sec},
        "log.initial.TGc.DeccDtEqtide": {"value": 3.004007e-17, "unit": 1 / u.sec},
        "log.initial.TGc.DMeanMotionDtEqtide": {
            "value": -9.830546e-22,
            "unit": 1 / u.sec**2,
        },
        "log.initial.TGc.DOrbPerDtEqtide": {"value": 1.581167e-10},
        "log.initial.TGc.EccTimeEqtide": {"value": 5.326219e15, "unit": u.sec},
        "log.initial.TGc.SemiTimeEqtide": {"value": 9.536819e15, "unit": u.sec},
        "log.initial.TGc.DHEccDtEqtide": {"value": -2.232412e-17, "unit": 1 / u.sec},
        "log.initial.TGc.DKEccDtEqtide": {"value": 2.010073e-17, "unit": 1 / u.sec},
        "log.initial.TGc.DXoblDtEqtide": {"value": 0.000000, "unit": 1 / u.sec},
        "log.initial.TGc.DYoblDtEqtide": {"value": 0.000000, "unit": 1 / u.sec},
        "log.initial.TGc.DZoblDtEqtide": {"value": 0.000000, "unit": 1 / u.sec},
        "log.initial.TGc.LockTime": {"value": -1.000000, "unit": u.sec},
        "log.initial.TGc.BodyDsemiDtEqtide": {"value": -1.000000},
        "log.initial.TGc.BodyDeccDt": {"value": -1.000000},
        "log.initial.TGc.DOblDtEqtide": {"value": 0.000000, "unit": u.rad / u.sec},
        "log.initial.TGc.DRotPerDtEqtide": {"value": 1.002411e-06},
        "log.initial.TGc.DRotRateDtEqtide": {
            "value": -8.437194e-16,
            "unit": 1 / u.sec**2,
        },
        "log.initial.TGc.EqRotRateDiscrete": {"value": 6.250142e-06, "unit": 1 / u.sec},
        "log.initial.TGc.EqRotPerDiscrete": {"value": 1.005287e06, "unit": u.sec},
        "log.initial.TGc.EqRotRateCont": {"value": 7.770177e-06, "unit": 1 / u.sec},
        "log.initial.TGc.EqRotPerCont": {"value": 8.086283e05, "unit": u.sec},
        "log.initial.TGc.EqRotPer": {"value": 1.005287e06, "unit": u.sec},
        "log.initial.TGc.EqTidePower": {"value": 0.000000, "unit": 1 / u.sec},
        "log.initial.TGc.GammaRot": {"value": -1.000000, "unit": u.sec},
        "log.initial.TGc.GammaOrb": {"value": -1.000000, "unit": u.sec},
        "log.initial.TGc.OceanK2": {"value": 0.010000},
        "log.initial.TGc.EnvTidalQ": {"value": -1.000000},
        "log.initial.TGc.OceanTidalQ": {"value": -1.000000},
        "log.initial.TGc.TideLock": {"value": 0.000000},
        "log.initial.TGc.RotTimeEqtide": {"value": 8.619223e10, "unit": u.sec},
        "log.initial.TGc.EnvK2": {"value": 0.010000},
        "log.initial.TGc.OblTimeEqtide": {"value": -1.000000},
        "log.initial.TGc.PowerEqtide": {"value": 5.387023e18, "unit": u.W},
        "log.initial.TGc.SurfEnFluxEqtide": {
            "value": 4683.535069,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.TGc.Sinc": {"value": 0.034899},
        "log.initial.TGc.Pinc": {"value": -0.033710},
        "log.initial.TGc.Qinc": {"value": -0.009033},
        "log.initial.TGc.DIncDtDistOrb": {
            "value": -2.724475e-11,
            "unit": u.rad / u.sec,
        },
        "log.initial.TGc.DSincDtDistOrb": {"value": -1.361408e-11, "unit": 1 / u.sec},
        "log.initial.TGc.DLongADtDistOrb": {
            "value": -4.987719e-10,
            "unit": u.rad / u.sec,
        },
        "log.initial.TGc.DLongPDtDistOrb": {
            "value": 1.643710e-10,
            "unit": u.rad / u.sec,
        },
        "log.initial.TGc.DHeccDtDistOrb": {"value": 6.915675e-12, "unit": 1 / u.sec},
        "log.initial.TGc.DKeccDtDistOrb": {"value": 2.916239e-11, "unit": 1 / u.sec},
        "log.initial.TGc.DPincDtDistOrb": {"value": 1.765542e-11, "unit": 1 / u.sec},
        "log.initial.TGc.DQincDtDistOrb": {"value": -1.329018e-11, "unit": 1 / u.sec},
        "log.initial.TGc.CassiniOne": {"value": 0.000000},
        "log.initial.TGc.CassiniTwo": {"value": 0.000000},
        "log.initial.TGc.DOblDtDistRot": {"value": 0.000000, "unit": u.rad},
        "log.initial.TGc.DPrecADtDistRot": {"value": 0.000000, "unit": u.rad / u.sec},
        "log.initial.TGc.DXoblDtDistRot": {"value": -2.655558e-11, "unit": 1 / u.sec},
        "log.initial.TGc.DYoblDtDistRot": {"value": -3.532139e-11, "unit": 1 / u.sec},
        "log.initial.TGc.DZoblDtDistRot": {"value": 0.000000, "unit": 1 / u.sec},
        "log.initial.TGc.XoblTimeDistRot": {"value": 3.765686e10, "unit": 1 / u.sec},
        "log.initial.TGc.YoblTimeDistRot": {"value": 2.831146e10, "unit": 1 / u.sec},
        "log.initial.TGc.DynEllip": {"value": 0.009975},
        "log.initial.TGc.PrecFNat": {"value": 8.355963e-09, "unit": u.rad / u.sec},
        "log.final.system.Age": {"value": 3.156076e13, "unit": u.sec, "rtol": 1e-4},
        "log.final.system.Time": {"value": 3.155760e09, "unit": u.sec, "rtol": 1e-4},
        "log.final.system.TotAngMom": {
            "value": 8.688022e39,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.system.TotEnergy": {
            "value": -1.657581e39,
            "unit": u.erg,
            "rtol": 1e-4,
        },
        "log.final.system.PotEnergy": {
            "value": -1.657580e39,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.system.KinEnergy": {
            "value": 1.389431e33,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.system.DeltaTime": {
            "value": 4.628368e04,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGstar.Mass": {"value": 1.590733e29, "unit": u.kg, "rtol": 1e-4},
        "log.final.TGstar.Obliquity": {"value": 0.000000, "unit": u.rad, "rtol": 1e-4},
        "log.final.TGstar.PrecA": {"value": 0.000000, "unit": u.rad, "rtol": 1e-4},
        "log.final.TGstar.Xobl": {"value": 0.000000, "rtol": 1e-4},
        "log.final.TGstar.Yobl": {"value": 0.000000, "rtol": 1e-4},
        "log.final.TGstar.Zobl": {"value": 1.000000, "rtol": 1e-4},
        "log.final.TGstar.Radius": {"value": 95.848284, "unit": u.Rearth, "rtol": 1e-4},
        "log.final.TGstar.RadGyra": {"value": 0.445942, "rtol": 1e-4},
        "log.final.TGstar.RotAngMom": {
            "value": 5.731739e39,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGstar.RotKinEnergy": {
            "value": 1.389431e33,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.TGstar.RotVel": {
            "value": 296.385042,
            "unit": u.m / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGstar.BodyType": {"value": 0.000000, "rtol": 1e-4},
        "log.final.TGstar.RotRate": {
            "value": 4.848201e-07,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGstar.RotPer": {"value": 149.998014, "unit": u.day, "rtol": 1e-4},
        "log.final.TGstar.Density": {
            "value": 166.219369,
            "unit": u.kg / u.m**3,
            "rtol": 1e-4,
        },
        "log.final.TGstar.SurfEnFluxTotal": {
            "value": 0.000200,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.TGstar.TidalQ": {"value": 1.000000e06, "rtol": 1e-4},
        "log.final.TGstar.ImK2": {"value": -5.000000e-07, "rtol": 1e-4},
        "log.final.TGstar.K2": {"value": 0.500000, "rtol": 1e-4},
        "log.final.TGstar.K2Man": {"value": 0.010000, "rtol": 1e-4},
        "log.final.TGstar.Imk2Man": {"value": 0.000000, "rtol": 1e-4},
        "log.final.TGstar.TidalQMantle": {"value": 100.000000, "rtol": 1e-4},
        "log.final.TGstar.HEcc": {"value": 0.000000, "rtol": 1e-4},
        "log.final.TGstar.HZLimitDryRunaway": {
            "value": 3.002072e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGstar.HZLimRecVenus": {
            "value": 2.704542e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGstar.HZLimRunaway": {
            "value": 3.557886e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGstar.HZLimMoistGreenhouse": {
            "value": 3.578559e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGstar.HZLimMaxGreenhouse": {
            "value": 6.881945e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGstar.HZLimEarlyMars": {
            "value": 7.505483e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGstar.Instellation": {
            "value": -1.000000,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.TGstar.KEcc": {"value": 0.000000, "rtol": 1e-4},
        "log.final.TGstar.Eccentricity": {"value": -1.000000, "rtol": 1e-4},
        "log.final.TGstar.OrbEnergy": {
            "value": 0.000000,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.TGstar.MeanMotion": {
            "value": -1.000000,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGstar.OrbPeriod": {"value": -1.000000, "unit": u.sec, "rtol": 1e-4},
        "log.final.TGstar.SemiMajorAxis": {
            "value": -1.000000,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGstar.CriticalSemiMajorAxis": {
            "value": -1.000000,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGstar.COPP": {"value": 0.000000, "rtol": 1e-4},
        "log.final.TGstar.OrbAngMom": {
            "value": 0.000000,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGstar.LongP": {"value": 0.000000, "unit": u.rad, "rtol": 1e-4},
        "log.final.TGstar.LXUVTot": {
            "value": 1.880010e22,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.TGstar.TotOrbEnergy": {
            "value": -1.426284e34,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.TGstar.OrbPotEnergy": {
            "value": -1.000000,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.TGstar.LostEnergy": {
            "value": 1.218546e34,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.TGstar.LostAngMom": {
            "value": 2.347849e33,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGstar.LockTime": {"value": -1.000000, "unit": u.sec, "rtol": 1e-4},
        "log.final.TGstar.BodyDsemiDtEqtide": {"value": -1.000000, "rtol": 1e-4},
        "log.final.TGstar.BodyDeccDt": {"value": -1.000000, "rtol": 1e-4},
        "log.final.TGstar.DOblDtEqtide": {
            "value": 0.000000,
            "unit": u.rad / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGstar.DRotPerDtEqtide": {"value": -1.502568e-13, "rtol": 1e-4},
        "log.final.TGstar.DRotRateDtEqtide": {
            "value": 5.621025e-27,
            "unit": 1 / u.sec**2,
            "rtol": 1e-4,
        },
        "log.final.TGstar.EqRotRateDiscrete": {
            "value": 1.407733e-05,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGstar.EqRotPerDiscrete": {
            "value": 4.463337e05,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGstar.EqRotRateCont": {
            "value": 1.551167e-05,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGstar.EqRotPerCont": {
            "value": 4.050618e05,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGstar.EqRotPer": {
            "value": 4.463337e05,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGstar.EqTidePower": {
            "value": 0.000000,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGstar.GammaRot": {"value": -1.000000, "unit": u.sec, "rtol": 1e-4},
        "log.final.TGstar.GammaOrb": {"value": -1.000000, "unit": u.sec, "rtol": 1e-4},
        "log.final.TGstar.OceanK2": {"value": 0.010000, "rtol": 1e-4},
        "log.final.TGstar.EnvTidalQ": {"value": -1.000000, "rtol": 1e-4},
        "log.final.TGstar.OceanTidalQ": {"value": -1.000000, "rtol": 1e-4},
        "log.final.TGstar.TideLock": {"value": 0.000000, "rtol": 1e-4},
        "log.final.TGstar.RotTimeEqtide": {
            "value": 5.350904e-27,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGstar.EnvK2": {"value": 0.010000, "rtol": 1e-4},
        "log.final.TGstar.OblTimeEqtide": {"value": -1.000000, "rtol": 1e-4},
        "log.final.TGstar.PowerEqtide": {
            "value": 9.416135e14,
            "unit": u.W,
            "rtol": 1e-4,
        },
        "log.final.TGstar.SurfEnFluxEqtide": {
            "value": 0.000200,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.TGstar.Luminosity": {
            "value": 0.048882,
            "unit": u.LSUN,
            "rtol": 1e-4,
        },
        "log.final.TGstar.LXUVStellar": {
            "value": 1.880010e22,
            "unit": u.W,
            "rtol": 1e-4,
        },
        "log.final.TGstar.Temperature": {
            "value": 2897.426047,
            "unit": u.K,
            "rtol": 1e-4,
        },
        "log.final.TGstar.LXUVFrac": {"value": 0.001000, "rtol": 1e-4},
        "log.final.TGstar.RossbyNumber": {"value": 2.105167, "rtol": 1e-4},
        "log.final.TGstar.DRotPerDtStellar": {"value": -5.634910e-08, "rtol": 1e-4},
        "log.final.TGb.Mass": {"value": 6.270795e24, "unit": u.kg, "rtol": 1e-4},
        "log.final.TGb.Obliquity": {"value": 0.542245, "unit": u.rad, "rtol": 1e-4},
        "log.final.TGb.PrecA": {"value": 3.434549, "unit": u.rad, "rtol": 1e-4},
        "log.final.TGb.Xobl": {"value": -0.494073, "rtol": 1e-4},
        "log.final.TGb.Yobl": {"value": -0.149030, "rtol": 1e-4},
        "log.final.TGb.Zobl": {"value": 0.856552, "rtol": 1e-4},
        "log.final.TGb.Radius": {"value": 7.653720e06, "unit": u.m, "rtol": 1e-4},
        "log.final.TGb.RadGyra": {"value": 0.400000, "rtol": 1e-4},
        "log.final.TGb.RotAngMom": {
            "value": 4.022309e33,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.RotKinEnergy": {
            "value": 1.376363e29,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.TGb.RotVel": {
            "value": 523.793649,
            "unit": u.m / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.BodyType": {"value": 0.000000, "rtol": 1e-4},
        "log.final.TGb.RotRate": {
            "value": 6.843648e-05,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.RotPer": {"value": 1.062621, "unit": u.day, "rtol": 1e-4},
        "log.final.TGb.Density": {
            "value": 3338.999118,
            "unit": u.kg / u.m**3,
            "rtol": 1e-4,
        },
        "log.final.TGb.SurfEnFluxTotal": {
            "value": 5473.112280,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.TGb.TidalQ": {"value": 100.000000, "rtol": 1e-4},
        "log.final.TGb.ImK2": {"value": -0.003000, "rtol": 1e-4},
        "log.final.TGb.K2": {"value": 0.300000, "rtol": 1e-4},
        "log.final.TGb.K2Man": {"value": 0.010000, "rtol": 1e-4},
        "log.final.TGb.Imk2Man": {"value": 0.000000, "rtol": 1e-4},
        "log.final.TGb.TidalQMantle": {"value": 100.000000, "rtol": 1e-4},
        "log.final.TGb.HEcc": {"value": 0.091315, "rtol": 1e-4},
        "log.final.TGb.HZLimitDryRunaway": {
            "value": 3.018301e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGb.HZLimRecVenus": {
            "value": 2.704542e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGb.HZLimRunaway": {"value": 3.557886e10, "unit": u.m, "rtol": 1e-4},
        "log.final.TGb.HZLimMoistGreenhouse": {
            "value": 3.578559e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGb.HZLimMaxGreenhouse": {
            "value": 6.881945e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGb.HZLimEarlyMars": {
            "value": 7.505483e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGb.Instellation": {
            "value": 1.058375e05,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.TGb.KEcc": {"value": -0.048856, "rtol": 1e-4},
        "log.final.TGb.Eccentricity": {"value": 0.103563, "rtol": 1e-4},
        "log.final.TGb.OrbEnergy": {
            "value": -8.830151e33,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.TGb.MeanMotion": {
            "value": 1.407733e-05,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.OrbPeriod": {"value": 4.463337e05, "unit": u.sec, "rtol": 1e-4},
        "log.final.TGb.SemiMajorAxis": {
            "value": 3.769868e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGb.CriticalSemiMajorAxis": {
            "value": -1.000000,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGb.COPP": {"value": -0.037835, "rtol": 1e-4},
        "log.final.TGb.OrbAngMom": {
            "value": 1.247775e39,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.ArgP": {"value": 2.505080, "unit": u.rad, "rtol": 1e-4},
        "log.final.TGb.Inc": {"value": 0.179378, "unit": u.rad, "rtol": 1e-4},
        "log.final.TGb.LongA": {"value": 5.840172, "unit": u.rad, "rtol": 1e-4},
        "log.final.TGb.MeanLongitude": {"value": 2.062067, "unit": u.rad, "rtol": 1e-4},
        "log.final.TGb.LongP": {"value": 2.062067, "unit": u.rad, "rtol": 1e-4},
        "log.final.TGb.TotOrbEnergy": {
            "value": -1.426284e34,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.TGb.OrbPotEnergy": {
            "value": -1.766030e34,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.TGb.LostEnergy": {
            "value": 1.391215e28,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.TGb.TidalRadius": {"value": 7.653720e06, "unit": u.m, "rtol": 1e-4},
        "log.final.TGb.DsemiDtEqtide": {
            "value": 4.746666e-07,
            "unit": u.m / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DeccDtEqtide": {
            "value": 2.723683e-17,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DMeanMotionDtEqtide": {
            "value": -2.658728e-21,
            "unit": 1 / u.sec**2,
            "rtol": 1e-4,
        },
        "log.final.TGb.DOrbPerDtEqtide": {"value": 8.429726e-11, "rtol": 1e-4},
        "log.final.TGb.EccTimeEqtide": {
            "value": 3.802317e15,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.SemiTimeEqtide": {
            "value": 7.942139e15,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DHEccDtEqtide": {
            "value": 2.401564e-17,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DKEccDtEqtide": {
            "value": -1.284889e-17,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DXoblDtEqtide": {
            "value": -3.658103e-12,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DYoblDtEqtide": {
            "value": -1.103412e-12,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DZoblDtEqtide": {
            "value": -2.302035e-12,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.LockTime": {"value": -1.000000, "unit": u.sec, "rtol": 1e-4},
        "log.final.TGb.BodyDsemiDtEqtide": {"value": -1.000000, "rtol": 1e-4},
        "log.final.TGb.BodyDeccDt": {"value": -1.000000, "rtol": 1e-4},
        "log.final.TGb.DOblDtEqtide": {
            "value": 4.460785e-12,
            "unit": u.rad / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DRotPerDtEqtide": {"value": 1.714884e-06, "rtol": 1e-4},
        "log.final.TGb.DRotRateDtEqtide": {
            "value": -1.278292e-15,
            "unit": 1 / u.sec**2,
            "rtol": 1e-4,
        },
        "log.final.TGb.EqRotRateDiscrete": {
            "value": 1.407733e-05,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.EqRotPerDiscrete": {
            "value": 4.463337e05,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.EqRotRateCont": {
            "value": 1.551167e-05,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.EqRotPerCont": {
            "value": 4.050618e05,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.EqRotPer": {"value": 4.463337e05, "unit": u.sec, "rtol": 1e-4},
        "log.final.TGb.EqTidePower": {
            "value": 0.000000,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.GammaRot": {"value": -1.000000, "unit": u.sec, "rtol": 1e-4},
        "log.final.TGb.GammaOrb": {"value": -1.000000, "unit": u.sec, "rtol": 1e-4},
        "log.final.TGb.OceanK2": {"value": 0.010000, "rtol": 1e-4},
        "log.final.TGb.EnvTidalQ": {"value": -1.000000, "rtol": 1e-4},
        "log.final.TGb.OceanTidalQ": {"value": -1.000000, "rtol": 1e-4},
        "log.final.TGb.TideLock": {"value": 0.000000, "rtol": 1e-4},
        "log.final.TGb.RotTimeEqtide": {
            "value": 5.353742e10,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.EnvK2": {"value": 0.010000, "rtol": 1e-4},
        "log.final.TGb.OblTimeEqtide": {"value": -1.000000, "rtol": 1e-4},
        "log.final.TGb.PowerEqtide": {"value": 4.028927e18, "unit": u.W, "rtol": 1e-4},
        "log.final.TGb.SurfEnFluxEqtide": {
            "value": 5473.112280,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.TGb.Sinc": {"value": 0.089569, "rtol": 1e-4},
        "log.final.TGb.Pinc": {"value": -0.038395, "rtol": 1e-4},
        "log.final.TGb.Qinc": {"value": 0.080922, "rtol": 1e-4},
        "log.final.TGb.DIncDtDistOrb": {
            "value": -7.744922e-12,
            "unit": u.rad / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DSincDtDistOrb": {
            "value": -3.856896e-12,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DLongADtDistOrb": {
            "value": -2.745234e-10,
            "unit": u.rad / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DLongPDtDistOrb": {
            "value": 3.848105e-10,
            "unit": u.rad / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DHeccDtDistOrb": {
            "value": -3.683808e-11,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DKeccDtDistOrb": {
            "value": -2.548830e-11,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DPincDtDistOrb": {
            "value": -2.056170e-11,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DQincDtDistOrb": {
            "value": -1.402485e-11,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.CassiniOne": {"value": 0.325099, "rtol": 1e-4},
        "log.final.TGb.CassiniTwo": {"value": -0.945680, "rtol": 1e-4},
        "log.final.TGb.DOblDtDistRot": {
            "value": 1.498009e-11,
            "unit": u.rad,
            "rtol": 1e-4,
        },
        "log.final.TGb.DPrecADtDistRot": {
            "value": 1.800466e-08,
            "unit": u.rad / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DXoblDtDistRot": {
            "value": 2.670947e-09,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DYoblDtDistRot": {
            "value": -8.899329e-09,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DZoblDtDistRot": {
            "value": -7.730633e-12,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.OblTimeDistRot": {
            "value": 2.097179e11,
            "unit": u.rad,
            "rtol": 1e-4,
        },
        "log.final.TGb.PrecATimeDistRot": {
            "value": 3.489756e08,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.XoblTimeDistRot": {
            "value": 3.743990e08,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.YoblTimeDistRot": {
            "value": 1.123680e08,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.ZoblTimeDistRot": {
            "value": 1.293555e11,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGb.DynEllip": {"value": 0.004781, "rtol": 1e-4},
        "log.final.TGb.PrecFNat": {
            "value": 1.807871e-08,
            "unit": u.rad / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.Mass": {"value": 6.629126e24, "unit": u.kg, "rtol": 1e-4},
        "log.final.TGc.Obliquity": {"value": 0.001855, "unit": u.rad, "rtol": 1e-4},
        "log.final.TGc.PrecA": {"value": 2.477072, "unit": u.rad, "rtol": 1e-4},
        "log.final.TGc.Xobl": {"value": -0.001460, "rtol": 1e-4},
        "log.final.TGc.Yobl": {"value": 0.001144, "rtol": 1e-4},
        "log.final.TGc.Zobl": {"value": 0.999998, "rtol": 1e-4},
        "log.final.TGc.Radius": {"value": 9.567150e06, "unit": u.m, "rtol": 1e-4},
        "log.final.TGc.RadGyra": {"value": 0.400000, "rtol": 1e-4},
        "log.final.TGc.RotAngMom": {
            "value": 6.793468e33,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.RotKinEnergy": {
            "value": 2.376904e29,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.TGc.RotVel": {
            "value": 669.472413,
            "unit": u.m / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.BodyType": {"value": 0.000000, "rtol": 1e-4},
        "log.final.TGc.RotRate": {
            "value": 6.997616e-05,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.RotPer": {"value": 1.039240, "unit": u.day, "rtol": 1e-4},
        "log.final.TGc.Density": {
            "value": 1807.257123,
            "unit": u.kg / u.m**3,
            "rtol": 1e-4,
        },
        "log.final.TGc.SurfEnFluxTotal": {
            "value": 4714.883886,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.TGc.TidalQ": {"value": 12.000000, "rtol": 1e-4},
        "log.final.TGc.ImK2": {"value": -0.025000, "rtol": 1e-4},
        "log.final.TGc.K2": {"value": 0.300000, "rtol": 1e-4},
        "log.final.TGc.K2Man": {"value": 0.010000, "rtol": 1e-4},
        "log.final.TGc.Imk2Man": {"value": 0.000000, "rtol": 1e-4},
        "log.final.TGc.TidalQMantle": {"value": 100.000000, "rtol": 1e-4},
        "log.final.TGc.HEcc": {"value": -0.050698, "rtol": 1e-4},
        "log.final.TGc.HZLimitDryRunaway": {
            "value": 3.054655e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGc.HZLimRecVenus": {
            "value": 2.704542e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGc.HZLimRunaway": {"value": 3.557886e10, "unit": u.m, "rtol": 1e-4},
        "log.final.TGc.HZLimMoistGreenhouse": {
            "value": 3.578559e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGc.HZLimMaxGreenhouse": {
            "value": 6.881945e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGc.HZLimEarlyMars": {
            "value": 7.505483e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGc.Instellation": {
            "value": 3.627976e04,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.TGc.KEcc": {"value": 0.177657, "rtol": 1e-4},
        "log.final.TGc.Eccentricity": {"value": 0.184749, "rtol": 1e-4},
        "log.final.TGc.OrbEnergy": {
            "value": -5.432685e33,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.TGc.MeanMotion": {
            "value": 6.250139e-06,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.OrbPeriod": {"value": 1.005287e06, "unit": u.sec, "rtol": 1e-4},
        "log.final.TGc.SemiMajorAxis": {
            "value": 6.477590e09,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGc.CriticalSemiMajorAxis": {
            "value": -1.000000,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.TGc.COPP": {"value": 0.000277, "rtol": 1e-4},
        "log.final.TGc.OrbAngMom": {
            "value": 1.708495e39,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.ArgP": {"value": 3.924108, "unit": u.rad, "rtol": 1e-4},
        "log.final.TGc.Inc": {"value": 0.075441, "unit": u.rad, "rtol": 1e-4},
        "log.final.TGc.LongA": {"value": 2.081097, "unit": u.rad, "rtol": 1e-4},
        "log.final.TGc.MeanLongitude": {
            "value": -0.277981,
            "unit": u.rad,
            "rtol": 1e-4,
        },
        "log.final.TGc.LongP": {"value": 6.005205, "unit": u.rad, "rtol": 1e-4},
        "log.final.TGc.TotOrbEnergy": {
            "value": -1.426284e34,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.TGc.OrbPotEnergy": {
            "value": -1.086537e34,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.TGc.LostEnergy": {
            "value": 1.713643e28,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.TGc.TidalRadius": {"value": 9.567150e06, "unit": u.m, "rtol": 1e-4},
        "log.final.TGc.DsemiDtEqtide": {
            "value": 7.349244e-07,
            "unit": u.m / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DeccDtEqtide": {
            "value": 3.468667e-17,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DMeanMotionDtEqtide": {
            "value": -1.063678e-21,
            "unit": 1 / u.sec**2,
            "rtol": 1e-4,
        },
        "log.final.TGc.DOrbPerDtEqtide": {"value": 1.710845e-10, "rtol": 1e-4},
        "log.final.TGc.EccTimeEqtide": {
            "value": 5.326231e15,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.SemiTimeEqtide": {
            "value": 8.813954e15,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DHEccDtEqtide": {
            "value": -9.518527e-18,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DKEccDtEqtide": {
            "value": 3.335510e-17,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DXoblDtEqtide": {
            "value": -7.384423e-15,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DYoblDtEqtide": {
            "value": 5.784766e-15,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DZoblDtEqtide": {
            "value": -1.739849e-17,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.LockTime": {"value": -1.000000, "unit": u.sec, "rtol": 1e-4},
        "log.final.TGc.BodyDsemiDtEqtide": {"value": -1.000000, "rtol": 1e-4},
        "log.final.TGc.BodyDeccDt": {"value": -1.000000, "rtol": 1e-4},
        "log.final.TGc.DOblDtEqtide": {
            "value": 9.380486e-15,
            "unit": u.rad / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DRotPerDtEqtide": {"value": 1.140742e-06, "rtol": 1e-4},
        "log.final.TGc.DRotRateDtEqtide": {
            "value": -8.890123e-16,
            "unit": 1 / u.sec**2,
            "rtol": 1e-4,
        },
        "log.final.TGc.EqRotRateDiscrete": {
            "value": 6.250139e-06,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.EqRotPerDiscrete": {
            "value": 1.005287e06,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.EqRotRateCont": {
            "value": 8.276789e-06,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.EqRotPerCont": {
            "value": 7.591332e05,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.EqRotPer": {"value": 1.005287e06, "unit": u.sec, "rtol": 1e-4},
        "log.final.TGc.EqTidePower": {
            "value": 0.000000,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.GammaRot": {"value": -1.000000, "unit": u.sec, "rtol": 1e-4},
        "log.final.TGc.GammaOrb": {"value": -1.000000, "unit": u.sec, "rtol": 1e-4},
        "log.final.TGc.OceanK2": {"value": 0.010000, "rtol": 1e-4},
        "log.final.TGc.EnvTidalQ": {"value": -1.000000, "rtol": 1e-4},
        "log.final.TGc.OceanTidalQ": {"value": -1.000000, "rtol": 1e-4},
        "log.final.TGc.TideLock": {"value": 0.000000, "rtol": 1e-4},
        "log.final.TGc.RotTimeEqtide": {
            "value": 7.871225e10,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.EnvK2": {"value": 0.010000, "rtol": 1e-4},
        "log.final.TGc.OblTimeEqtide": {"value": -1.000000, "rtol": 1e-4},
        "log.final.TGc.PowerEqtide": {"value": 5.423080e18, "unit": u.W, "rtol": 1e-4},
        "log.final.TGc.SurfEnFluxEqtide": {
            "value": 4714.883886,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.TGc.Sinc": {"value": 0.037712, "rtol": 1e-4},
        "log.final.TGc.Pinc": {"value": 0.032907, "rtol": 1e-4},
        "log.final.TGc.Qinc": {"value": -0.018420, "rtol": 1e-4},
        "log.final.TGc.DIncDtDistOrb": {
            "value": 1.653610e-11,
            "unit": u.rad / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DSincDtDistOrb": {
            "value": 8.262169e-12,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DLongADtDistOrb": {
            "value": -4.277927e-10,
            "unit": u.rad / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DLongPDtDistOrb": {
            "value": 1.813329e-10,
            "unit": u.rad / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DHeccDtDistOrb": {
            "value": 3.034204e-11,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DKeccDtDistOrb": {
            "value": 1.575669e-11,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DPincDtDistOrb": {
            "value": 1.508946e-11,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DQincDtDistOrb": {
            "value": 1.004190e-11,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.CassiniOne": {"value": 0.959339, "rtol": 1e-4},
        "log.final.TGc.CassiniTwo": {"value": 0.282255, "rtol": 1e-4},
        "log.final.TGc.DOblDtDistRot": {
            "value": -3.440014e-11,
            "unit": u.rad,
            "rtol": 1e-4,
        },
        "log.final.TGc.DPrecADtDistRot": {
            "value": 1.428780e-08,
            "unit": u.rad / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DXoblDtDistRot": {
            "value": 1.073788e-11,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DYoblDtDistRot": {
            "value": -4.207532e-11,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DZoblDtDistRot": {
            "value": 6.380379e-14,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.OblTimeDistRot": {
            "value": 9.132499e10,
            "unit": u.rad,
            "rtol": 1e-4,
        },
        "log.final.TGc.PrecATimeDistRot": {
            "value": 4.397587e08,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.XoblTimeDistRot": {
            "value": 9.312822e10,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.YoblTimeDistRot": {
            "value": 2.376690e10,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.ZoblTimeDistRot": {
            "value": 1.567305e13,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.TGc.DynEllip": {"value": 0.009236, "rtol": 1e-4},
        "log.final.TGc.PrecFNat": {
            "value": 8.147206e-09,
            "unit": u.rad / u.sec,
            "rtol": 1e-4,
        },
    }
)
class TestCassiniMulti(Benchmark):
    pass
