import astropy.units as u
from benchmark import Benchmark, benchmark


@benchmark(
    {
        "log.initial.system.Age": {"value": 1.893456e14, "unit": u.sec},
        "log.initial.system.Time": {"value": -0.000000, "unit": u.sec},
        "log.initial.system.TotAngMom": {
            "value": 1.704724e42,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.system.TotEnergy": {"value": -1.266740e41, "unit": u.erg},
        "log.initial.system.PotEnergy": {"value": -1.266789e41, "unit": u.Joule},
        "log.initial.system.KinEnergy": {"value": 5.216560e36, "unit": u.Joule},
        "log.initial.system.DeltaTime": {"value": 0.000000, "unit": u.sec},
        "log.initial.star.Mass": {"value": 1.664668e30, "unit": u.kg},
        "log.initial.star.Radius": {"value": 137.345736, "unit": u.Rearth},
        "log.initial.star.RadGyra": {"value": 0.451745},
        "log.initial.star.RotAngMom": {
            "value": 1.649189e42,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.star.RotVel": {"value": 5541.793158, "unit": u.m / u.sec},
        "log.initial.star.BodyType": {"value": 0.000000},
        "log.initial.star.RotRate": {"value": 6.326213e-06, "unit": 1 / u.sec},
        "log.initial.star.RotPer": {"value": 11.495353, "unit": u.day},
        "log.initial.star.Density": {"value": 591.179639, "unit": u.kg / u.m**3},
        "log.initial.star.HZLimitDryRunaway": {"value": 8.673793e10, "unit": u.m},
        "log.initial.star.HZLimRecVenus": {"value": 7.601779e10, "unit": u.m},
        "log.initial.star.HZLimRunaway": {"value": 1.008977e11, "unit": u.m},
        "log.initial.star.HZLimMoistGreenhouse": {"value": 1.005837e11, "unit": u.m},
        "log.initial.star.HZLimMaxGreenhouse": {"value": 1.842211e11, "unit": u.m},
        "log.initial.star.HZLimEarlyMars": {"value": 2.009395e11, "unit": u.m},
        "log.initial.star.Instellation": {
            "value": -1.000000,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.star.CriticalSemiMajorAxis": {"value": -1.000000, "unit": u.m},
        "log.initial.star.LXUVTot": {"value": 9.613990e-05, "unit": u.LSUN},
        "log.initial.star.LostEnergy": {"value": 5.562685e-309, "unit": u.Joule},
        "log.initial.star.LostAngMom": {
            "value": 5.562685e-309,
            "unit": (u.kg * u.m**2) / u.sec,
        },
        "log.initial.star.EscapeVelocity": {"value": 5.036487e05, "unit": u.m / u.sec},
        "log.initial.star.Luminosity": {"value": 0.408063, "unit": u.LSUN},
        "log.initial.star.LXUVStellar": {"value": 9.613990e-05, "unit": u.LSUN},
        "log.initial.star.Temperature": {"value": 4113.322048, "unit": u.K},
        "log.initial.star.LXUVFrac": {"value": 7.136205e-31},
        "log.initial.star.RossbyNumber": {"value": 0.300883},
        "log.initial.star.DRotPerDtStellar": {"value": -3.082129e-09},
        "log.initial.star.LEUVStellar": {"value": 5.043843e-05, "unit": u.LSUN},
        "log.initial.star.LXRayStellar": {"value": 4.570147e-05, "unit": u.LSUN},
        "log.initial.star.WindTorque": {"value": 1.471779e26},
        "log.initial.fixed.Mass": {"value": 4.292131, "unit": u.Mearth},
        "log.initial.fixed.Radius": {"value": 1.562927e07, "unit": u.m},
        "log.initial.fixed.RadGyra": {"value": 0.500000},
        "log.initial.fixed.BodyType": {"value": 0.000000},
        "log.initial.fixed.Density": {"value": 1602.882228, "unit": u.kg / u.m**3},
        "log.initial.fixed.HZLimitDryRunaway": {"value": 8.673793e10, "unit": u.m},
        "log.initial.fixed.HZLimRecVenus": {"value": 7.601779e10, "unit": u.m},
        "log.initial.fixed.HZLimRunaway": {"value": 1.008977e11, "unit": u.m},
        "log.initial.fixed.HZLimMoistGreenhouse": {"value": 1.005837e11, "unit": u.m},
        "log.initial.fixed.HZLimMaxGreenhouse": {"value": 1.842211e11, "unit": u.m},
        "log.initial.fixed.HZLimEarlyMars": {"value": 2.009395e11, "unit": u.m},
        "log.initial.fixed.Instellation": {
            "value": 1.119608e05,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.fixed.MeanMotion": {"value": 9.711229e-06, "unit": 1 / u.sec},
        "log.initial.fixed.OrbPeriod": {"value": 6.470021e05, "unit": u.sec},
        "log.initial.fixed.SemiMajorAxis": {"value": 1.056161e10, "unit": u.m},
        "log.initial.fixed.LXUVTot": {"value": -1.000000, "unit": u.W},
        "log.initial.fixed.EscapeVelocity": {"value": 1.479623e04, "unit": u.m / u.sec},
        "log.initial.fixed.SurfWaterMass": {"value": 0.000000, "unit": u.kg},
        "log.initial.fixed.EnvelopeMass": {"value": 0.035000, "unit": u.Mearth},
        "log.initial.fixed.OxygenMass": {"value": 0.000000, "unit": u.kg},
        "log.initial.fixed.RGLimit": {"value": 9.481046e10, "unit": u.m},
        "log.initial.fixed.XO": {"value": 0.000000},
        "log.initial.fixed.EtaO": {"value": 0.000000},
        "log.initial.fixed.PlanetRadius": {"value": 2.450459, "unit": u.Rearth},
        "log.initial.fixed.OxygenMantleMass": {"value": 0.000000, "unit": u.kg},
        "log.initial.fixed.RadXUV": {"value": -1.000000, "unit": u.m},
        "log.initial.fixed.RadSolid": {"value": -1.000000, "unit": u.m},
        "log.initial.fixed.ScaleHeight": {"value": -1.000000, "unit": u.m},
        "log.initial.fixed.ThermTemp": {"value": 880.000000, "unit": u.K},
        "log.initial.fixed.PresSurf": {"value": -1.000000, "unit": u.Pa},
        "log.initial.fixed.DEnvMassDt": {"value": -4.429575e07, "unit": u.kg / u.sec},
        "log.initial.fixed.FXUV": {"value": 26.378060, "unit": u.W / u.m**2},
        "log.initial.fixed.AtmXAbsEffH2O": {"value": 0.300000},
        "log.initial.fixed.RocheRadius": {"value": 28.564368, "unit": u.Rearth},
        "log.initial.fixed.BondiRadius": {"value": 2.418331e08, "unit": u.m},
        "log.initial.fixed.HEscapeRegime": {"value": 6.000000},
        "log.initial.fixed.RRCriticalFlux": {"value": 4.597835, "unit": u.W / u.m**2},
        "log.initial.fixed.CrossoverMass": {"value": 0.000000, "unit": u.kg},
        "log.initial.fixed.WaterEscapeRegime": {"value": 8.000000},
        "log.initial.fixed.FXUVCRITDRAG": {"value": 0.333483, "unit": u.W / u.m**2},
        "log.initial.fixed.HREFFLUX": {
            "value": 1.248672e19,
            "unit": 1 / u.m**2 / u.sec,
        },
        "log.initial.fixed.XO2": {"value": 0.000000},
        "log.initial.fixed.XH2O": {"value": 0.000000},
        "log.initial.fixed.HDiffFlux": {
            "value": 1.356178e17,
            "unit": 1 / u.m**2 / u.sec,
        },
        "log.initial.fixed.HRefODragMod": {"value": 1.000000},
        "log.initial.fixed.KTide": {"value": 0.871635},
        "log.initial.fixed.CumulativeXUVFlux": {
            "value": 0.000000,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.fixed.RunawayGreenhouseFlux": {
            "value": 1389.356416,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.fixed.RGDuration": {"value": 0.00000e00, "unit": u.yr},
        "log.initial.root.Mass": {"value": 4.292131, "unit": u.Mearth},
        "log.initial.root.Radius": {"value": 1.275620e07, "unit": u.m},
        "log.initial.root.RadGyra": {"value": 0.500000},
        "log.initial.root.BodyType": {"value": 0.000000},
        "log.initial.root.Density": {"value": 2948.178470, "unit": u.kg / u.m**3},
        "log.initial.root.HZLimitDryRunaway": {"value": 8.673793e10, "unit": u.m},
        "log.initial.root.HZLimRecVenus": {"value": 7.601779e10, "unit": u.m},
        "log.initial.root.HZLimRunaway": {"value": 1.008977e11, "unit": u.m},
        "log.initial.root.HZLimMoistGreenhouse": {"value": 1.005837e11, "unit": u.m},
        "log.initial.root.HZLimMaxGreenhouse": {"value": 1.842211e11, "unit": u.m},
        "log.initial.root.HZLimEarlyMars": {"value": 2.009395e11, "unit": u.m},
        "log.initial.root.Instellation": {
            "value": 1.119608e05,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.root.MeanMotion": {"value": 9.711229e-06, "unit": 1 / u.sec},
        "log.initial.root.OrbPeriod": {"value": 6.470021e05, "unit": u.sec},
        "log.initial.root.SemiMajorAxis": {"value": 1.056161e10, "unit": u.m},
        "log.initial.root.LXUVTot": {"value": -1.000000, "unit": u.W},
        "log.initial.root.EscapeVelocity": {"value": 1.637796e04, "unit": u.m / u.sec},
        "log.initial.root.SurfWaterMass": {"value": 0.000000, "unit": u.kg},
        "log.initial.root.EnvelopeMass": {"value": 0.016648, "unit": u.Mearth},
        "log.initial.root.OxygenMass": {"value": 0.000000, "unit": u.kg},
        "log.initial.root.RGLimit": {"value": 9.481046e10, "unit": u.m},
        "log.initial.root.XO": {"value": 0.000000},
        "log.initial.root.EtaO": {"value": 0.000000},
        "log.initial.root.PlanetRadius": {"value": 2.000000, "unit": u.Rearth},
        "log.initial.root.OxygenMantleMass": {"value": 0.000000, "unit": u.kg},
        "log.initial.root.RadXUV": {"value": -1.000000, "unit": u.m},
        "log.initial.root.RadSolid": {"value": -1.000000, "unit": u.m},
        "log.initial.root.ScaleHeight": {"value": -1.000000, "unit": u.m},
        "log.initial.root.ThermTemp": {"value": 880.000000, "unit": u.K},
        "log.initial.root.PresSurf": {"value": -1.000000, "unit": u.Pa},
        "log.initial.root.DEnvMassDt": {"value": -3.266149e07, "unit": u.kg / u.sec},
        "log.initial.root.FXUV": {"value": 26.378060, "unit": u.W / u.m**2},
        "log.initial.root.AtmXAbsEffH2O": {"value": 0.300000},
        "log.initial.root.RocheRadius": {"value": 28.564368, "unit": u.Rearth},
        "log.initial.root.BondiRadius": {"value": 2.418331e08, "unit": u.m},
        "log.initial.root.HEscapeRegime": {"value": 6.000000},
        "log.initial.root.RRCriticalFlux": {"value": 8.919159, "unit": u.W / u.m**2},
        "log.initial.root.CrossoverMass": {"value": 0.000000, "unit": u.kg},
        "log.initial.root.WaterEscapeRegime": {"value": 8.000000},
        "log.initial.root.FXUVCRITDRAG": {"value": 0.613375, "unit": u.W / u.m**2},
        "log.initial.root.HREFFLUX": {
            "value": 9.923660e18,
            "unit": 1 / u.m**2 / u.sec,
        },
        "log.initial.root.XO2": {"value": 0.000000},
        "log.initial.root.XH2O": {"value": 0.000000},
        "log.initial.root.HDiffFlux": {
            "value": 2.035877e17,
            "unit": 1 / u.m**2 / u.sec,
        },
        "log.initial.root.HRefODragMod": {"value": 1.000000},
        "log.initial.root.KTide": {"value": 0.895146},
        "log.initial.root.CumulativeXUVFlux": {
            "value": 0.000000,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.root.RunawayGreenhouseFlux": {
            "value": 1389.356416,
            "unit": u.kg / u.sec**3,
        },
        "log.initial.root.RGDuration": {"value": 0.00000e00, "unit": u.yr},
        "log.final.system.Age": {"value": 1.577880e14, "unit": u.sec, "rtol": 1e-4},
        "log.final.system.Time": {"value": -3.155760e13, "unit": u.sec, "rtol": 1e-4},
        "log.final.system.TotAngMom": {
            "value": 1.705205e42,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.system.TotEnergy": {
            "value": -1.266478e41,
            "unit": u.erg,
            "rtol": 1e-4,
        },
        "log.final.system.PotEnergy": {
            "value": -1.198541e41,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.system.KinEnergy": {
            "value": 4.686544e36,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.star.Mass": {"value": 1.664668e30, "unit": u.kg, "rtol": 1e-4},
        "log.final.star.Radius": {"value": 145.166579, "unit": u.Rearth, "rtol": 1e-4},
        "log.final.star.RadGyra": {"value": 0.452229, "rtol": 1e-4},
        "log.final.star.RotAngMom": {
            "value": 1.653948e42,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.star.RotVel": {
            "value": 5247.095506,
            "unit": u.m / u.sec,
            "rtol": 1e-4,
        },
        "log.final.star.BodyType": {"value": 0.000000, "rtol": 1e-4},
        "log.final.star.RotRate": {
            "value": 5.667102e-06,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.star.RotPer": {"value": 12.832318, "unit": u.day, "rtol": 1e-4},
        "log.final.star.Density": {
            "value": 500.685584,
            "unit": u.kg / u.m**3,
            "rtol": 1e-4,
        },
        "log.final.star.HZLimitDryRunaway": {
            "value": 9.225026e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.star.HZLimRecVenus": {
            "value": 8.081979e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.star.HZLimRunaway": {
            "value": 1.072747e11,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.star.HZLimMoistGreenhouse": {
            "value": 1.069375e11,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.star.HZLimMaxGreenhouse": {
            "value": 1.957535e11,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.star.HZLimEarlyMars": {
            "value": 2.135189e11,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.star.Instellation": {
            "value": -1.000000,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.star.CriticalSemiMajorAxis": {
            "value": -1.000000,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.star.LXUVTot": {"value": 9.043956e-05, "unit": u.LSUN, "rtol": 1e-4},
        "log.final.star.LostEnergy": {
            "value": -6.798103e39,
            "unit": u.Joule,
            "rtol": 1e-4,
        },
        "log.final.star.LostAngMom": {
            "value": -4.279543e39,
            "unit": (u.kg * u.m**2) / u.sec,
            "rtol": 1e-4,
        },
        "log.final.star.EscapeVelocity": {
            "value": 4.898939e05,
            "unit": u.m / u.sec,
            "rtol": 1e-4,
        },
        "log.final.star.Luminosity": {"value": 0.461577, "unit": u.LSUN, "rtol": 1e-4},
        "log.final.star.LXUVStellar": {
            "value": 9.043956e-05,
            "unit": u.LSUN,
            "rtol": 1e-4,
        },
        "log.final.star.Temperature": {"value": 4125.375734, "unit": u.K, "rtol": 1e-4},
        "log.final.star.LXUVFrac": {"value": 5.065244e-31, "rtol": 1e-4},
        "log.final.star.RossbyNumber": {"value": 0.337966, "rtol": 1e-4},
        "log.final.star.DRotPerDtStellar": {"value": -4.203772e-09, "rtol": 1e-4},
        "log.final.star.LEUVStellar": {
            "value": 4.893485e-05,
            "unit": u.LSUN,
            "rtol": 1e-4,
        },
        "log.final.star.LXRayStellar": {
            "value": 4.150471e-05,
            "unit": u.LSUN,
            "rtol": 1e-4,
        },
        "log.final.star.WindTorque": {"value": 1.241346e26, "rtol": 1e-4},
        "log.final.fixed.Mass": {"value": 4.292362, "unit": u.Mearth, "rtol": 1e-4},
        "log.final.fixed.Radius": {"value": 1.566082e07, "unit": u.m, "rtol": 1e-4},
        "log.final.fixed.RadGyra": {"value": 0.500000, "rtol": 1e-4},
        "log.final.fixed.BodyType": {"value": 0.000000, "rtol": 1e-4},
        "log.final.fixed.Density": {
            "value": 1593.299310,
            "unit": u.kg / u.m**3,
            "rtol": 1e-4,
        },
        "log.final.fixed.HZLimitDryRunaway": {
            "value": 9.225026e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.fixed.HZLimRecVenus": {
            "value": 8.081979e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.fixed.HZLimRunaway": {
            "value": 1.072747e11,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.fixed.HZLimMoistGreenhouse": {
            "value": 1.069375e11,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.fixed.HZLimMaxGreenhouse": {
            "value": 1.957535e11,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.fixed.HZLimEarlyMars": {
            "value": 2.135189e11,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.fixed.Instellation": {
            "value": 1.266435e05,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.fixed.MeanMotion": {
            "value": 9.711229e-06,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.fixed.OrbPeriod": {
            "value": 6.470021e05,
            "unit": u.sec,
            "rtol": 1e-4,
        },
        "log.final.fixed.SemiMajorAxis": {
            "value": 1.056161e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.fixed.LXUVTot": {"value": -1.000000, "unit": u.W, "rtol": 1e-4},
        "log.final.fixed.EscapeVelocity": {
            "value": 1.478171e04,
            "unit": u.m / u.sec,
            "rtol": 1e-4,
        },
        "log.final.fixed.SurfWaterMass": {
            "value": 0.000000,
            "unit": u.kg,
            "rtol": 1e-4,
        },
        "log.final.fixed.EnvelopeMass": {
            "value": 0.035231,
            "unit": u.Mearth,
            "rtol": 1e-4,
        },
        "log.final.fixed.OxygenMass": {"value": 0.000000, "unit": u.kg, "rtol": 1e-4},
        "log.final.fixed.RGLimit": {"value": 1.008057e11, "unit": u.m, "rtol": 1e-4},
        "log.final.fixed.XO": {"value": 0.000000, "rtol": 1e-4},
        "log.final.fixed.EtaO": {"value": 0.000000, "rtol": 1e-4},
        "log.final.fixed.PlanetRadius": {
            "value": 2.455406,
            "unit": u.Rearth,
            "rtol": 1e-4,
        },
        "log.final.fixed.OxygenMantleMass": {
            "value": 0.000000,
            "unit": u.kg,
            "rtol": 1e-4,
        },
        "log.final.fixed.RadXUV": {"value": -1.000000, "unit": u.m, "rtol": 1e-4},
        "log.final.fixed.RadSolid": {"value": -1.000000, "unit": u.m, "rtol": 1e-4},
        "log.final.fixed.ScaleHeight": {"value": -1.000000, "unit": u.m, "rtol": 1e-4},
        "log.final.fixed.ThermTemp": {"value": 880.000000, "unit": u.K, "rtol": 1e-4},
        "log.final.fixed.PresSurf": {"value": -1.000000, "unit": u.Pa, "rtol": 1e-4},
        "log.final.fixed.DEnvMassDt": {
            "value": 4.309387e07,
            "unit": u.kg / u.sec,
            "rtol": 1e-4,
        },
        "log.final.fixed.FXUV": {
            "value": 24.814049,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.fixed.AtmXAbsEffH2O": {"value": 0.300000, "rtol": 1e-4},
        "log.final.fixed.RocheRadius": {
            "value": 28.564880,
            "unit": u.Rearth,
            "rtol": 1e-4,
        },
        "log.final.fixed.BondiRadius": {
            "value": 2.345539e08,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.fixed.HEscapeRegime": {"value": 6.000000, "rtol": 1e-4},
        "log.final.fixed.RRCriticalFlux": {
            "value": 4.567913,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.fixed.CrossoverMass": {
            "value": 0.000000,
            "unit": u.kg,
            "rtol": 1e-4,
        },
        "log.final.fixed.WaterEscapeRegime": {"value": 8.000000, "rtol": 1e-4},
        "log.final.fixed.FXUVCRITDRAG": {
            "value": 0.331507,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.fixed.HREFFLUX": {
            "value": 1.177289e19,
            "unit": 1 / u.m**2 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.fixed.XO2": {"value": 0.000000, "rtol": 1e-4},
        "log.final.fixed.XH2O": {"value": 0.000000, "rtol": 1e-4},
        "log.final.fixed.HDiffFlux": {
            "value": 1.350792e17,
            "unit": 1 / u.m**2 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.fixed.HRefODragMod": {"value": 1.000000, "rtol": 1e-4},
        "log.final.fixed.KTide": {"value": 0.871379, "rtol": 1e-4},
        "log.final.fixed.CumulativeXUVFlux": {
            "value": 8.502780e14,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.fixed.RunawayGreenhouseFlux": {
            "value": 1390.185532,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.fixed.RGDuration": {"value": 0.00000e00, "unit": u.yr, "rtol": 1e-4},
        "log.final.root.Mass": {"value": 4.292302, "unit": u.Mearth, "rtol": 1e-4},
        "log.final.root.Radius": {"value": 1.279173e07, "unit": u.m, "rtol": 1e-4},
        "log.final.root.RadGyra": {"value": 0.500000, "rtol": 1e-4},
        "log.final.root.BodyType": {"value": 0.000000, "rtol": 1e-4},
        "log.final.root.Density": {
            "value": 2923.793804,
            "unit": u.kg / u.m**3,
            "rtol": 1e-4,
        },
        "log.final.root.HZLimitDryRunaway": {
            "value": 9.225026e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.root.HZLimRecVenus": {
            "value": 8.081979e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.root.HZLimRunaway": {
            "value": 1.072747e11,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.root.HZLimMoistGreenhouse": {
            "value": 1.069375e11,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.root.HZLimMaxGreenhouse": {
            "value": 1.957535e11,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.root.HZLimEarlyMars": {
            "value": 2.135189e11,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.root.Instellation": {
            "value": 1.266435e05,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.root.MeanMotion": {
            "value": 9.711229e-06,
            "unit": 1 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.root.OrbPeriod": {"value": 6.470021e05, "unit": u.sec, "rtol": 1e-4},
        "log.final.root.SemiMajorAxis": {
            "value": 1.056161e10,
            "unit": u.m,
            "rtol": 1e-4,
        },
        "log.final.root.LXUVTot": {"value": -1.000000, "unit": u.W, "rtol": 1e-4},
        "log.final.root.EscapeVelocity": {
            "value": 1.635552e04,
            "unit": u.m / u.sec,
            "rtol": 1e-4,
        },
        "log.final.root.SurfWaterMass": {"value": 0.000000, "unit": u.kg, "rtol": 1e-4},
        "log.final.root.EnvelopeMass": {
            "value": 0.016818,
            "unit": u.Mearth,
            "rtol": 1e-4,
        },
        "log.final.root.OxygenMass": {"value": 0.000000, "unit": u.kg, "rtol": 1e-4},
        "log.final.root.RGLimit": {"value": 1.008058e11, "unit": u.m, "rtol": 1e-4},
        "log.final.root.XO": {"value": 0.000000, "rtol": 1e-4},
        "log.final.root.EtaO": {"value": 0.000000, "rtol": 1e-4},
        "log.final.root.PlanetRadius": {
            "value": 2.005571,
            "unit": u.Rearth,
            "rtol": 1e-4,
        },
        "log.final.root.OxygenMantleMass": {
            "value": 0.000000,
            "unit": u.kg,
            "rtol": 1e-4,
        },
        "log.final.root.RadXUV": {"value": -1.000000, "unit": u.m, "rtol": 1e-4},
        "log.final.root.RadSolid": {"value": -1.000000, "unit": u.m, "rtol": 1e-4},
        "log.final.root.ScaleHeight": {"value": -1.000000, "unit": u.m, "rtol": 1e-4},
        "log.final.root.ThermTemp": {"value": 880.000000, "unit": u.K, "rtol": 1e-4},
        "log.final.root.PresSurf": {"value": -1.000000, "unit": u.Pa, "rtol": 1e-4},
        "log.final.root.DEnvMassDt": {
            "value": 3.181177e07,
            "unit": u.kg / u.sec,
            "rtol": 1e-4,
        },
        "log.final.root.FXUV": {
            "value": 24.814049,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.root.AtmXAbsEffH2O": {"value": 0.300000, "rtol": 1e-4},
        "log.final.root.RocheRadius": {
            "value": 28.564746,
            "unit": u.Rearth,
            "rtol": 1e-4,
        },
        "log.final.root.BondiRadius": {"value": 2.345506e08, "unit": u.m, "rtol": 1e-4},
        "log.final.root.HEscapeRegime": {"value": 6.000000, "rtol": 1e-4},
        "log.final.root.RRCriticalFlux": {
            "value": 8.840013,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.root.CrossoverMass": {"value": 0.000000, "unit": u.kg, "rtol": 1e-4},
        "log.final.root.WaterEscapeRegime": {"value": 8.000000, "rtol": 1e-4},
        "log.final.root.FXUVCRITDRAG": {
            "value": 0.608326,
            "unit": u.W / u.m**2,
            "rtol": 1e-4,
        },
        "log.final.root.HREFFLUX": {
            "value": 9.363929e18,
            "unit": 1 / u.m**2 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.root.XO2": {"value": 0.000000, "rtol": 1e-4},
        "log.final.root.XH2O": {"value": 0.000000, "rtol": 1e-4},
        "log.final.root.HDiffFlux": {
            "value": 2.024662e17,
            "unit": 1 / u.m**2 / u.sec,
            "rtol": 1e-4,
        },
        "log.final.root.HRefODragMod": {"value": 1.000000, "rtol": 1e-4},
        "log.final.root.KTide": {"value": 0.894856, "rtol": 1e-4},
        "log.final.root.CumulativeXUVFlux": {
            "value": 8.502780e14,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.root.RunawayGreenhouseFlux": {
            "value": 1390.184676,
            "unit": u.kg / u.sec**3,
            "rtol": 1e-4,
        },
        "log.final.root.RGDuration": {"value": 0.00000e00, "unit": u.yr, "rtol": 1e-4},
    }
)
class Test_Backward(Benchmark):
    pass
