#!/bin/sh

# CD into our working directory
cd /usr/lusers/rodluger/src/proxima/uncert

if [ $NODES -eq 1 ]; then
  # Run on a single node with Python multiprocessing
  python uncert.py -r -n $NAME -s $NSTEPS -w $NWALK -b $NBURN -e $NSAMPLES -o $OCEANS -h $HYDROGEN -x $EPSILON -m $MAGMA
else
  # Run on multiple nodes with MPI
  mpirun -np $PBS_NP python uncert.py -r -n $NAME -s $NSTEPS -w $NWALK -b $NBURN -e $NSAMPLES -o $OCEANS -h $HYDROGEN -x $EPSILON -m $MAGMA
fi