# -*- coding: iso-8859-1 -*-
import numpy as np
import matplotlib.pyplot as plt
import vplot

out = vplot.GetOutput()

fig = plt.figure(figsize=(8.5,8))
fig.subplots_adjust(hspace=0.1)

t, a, e, inc, longa, argp, ma = np.loadtxt('hnbdata/1.dat',unpack=True)
ax=plt.subplot(4,2,1)
plt.plot(out.Mercury.Time/1e6,out.Mercury.Eccentricity,'k-',label='DistOrb',zorder=100)
plt.plot(t/1e6,e,'0.5',label='HNBody')
plt.xlim(0,1)
plt.ylabel('$e$')
plt.xticks(visible=False)
plt.text(0.05,0.85,'Mercury',transform=ax.transAxes)

plt.subplot(4,2,2)
plt.plot(out.Mercury.Time/1e6,out.Mercury.Inc,'k-',label='DistOrb',zorder=100)
plt.plot(t/1e6,inc,'0.5',label='HNBody')
plt.xlim(0,1)
plt.ylabel('$i$ ($^{\circ}$)')
plt.xticks(visible=False)
plt.legend(loc='upper right',fontsize=10)

t, a, e, inc, longa, argp, ma = np.loadtxt('hnbdata/2.dat',unpack=True)
ax=plt.subplot(4,2,3)
plt.plot(out.Venus.Time/1e6,out.Venus.Eccentricity,'k-',label='DistOrb',zorder=100)
plt.plot(t/1e6,e,'0.5',label='HNBody')
plt.xlim(0,1)
plt.ylabel('$e$')
plt.xticks(visible=False)
plt.text(0.05,0.85,'Venus',transform=ax.transAxes)

plt.subplot(4,2,4)
plt.plot(out.Venus.Time/1e6,out.Venus.Inc,'k-',label='DistOrb',zorder=100)
plt.plot(t/1e6,inc,'0.5',label='HNBody')
plt.xlim(0,1)
plt.ylabel('$i$ ($^{\circ}$)')
plt.xticks(visible=False)

t, a, e, inc, longa, argp, ma = np.loadtxt('hnbdata/3.dat',unpack=True)
ax=plt.subplot(4,2,5)
plt.plot(out.Earth.Time/1e6,out.Earth.Eccentricity,'k-',label='DistOrb',zorder=100)
plt.plot(t/1e6,e,'0.5',label='HNBody')
plt.xlim(0,1)
plt.ylabel('$e$')
plt.xticks(visible=False)
plt.text(0.05,0.85,'Earth',transform=ax.transAxes)

plt.subplot(4,2,6)
plt.plot(out.Earth.Time/1e6,out.Earth.Inc,'k-',label='DistOrb',zorder=100)
plt.plot(t/1e6,inc,'0.5',label='HNBody')
plt.xlim(0,1)
plt.ylabel('$i$ ($^{\circ}$)')
plt.xticks(visible=False)

t, a, e, inc, longa, argp, ma = np.loadtxt('hnbdata/4.dat',unpack=True)
ax=plt.subplot(4,2,7)
plt.plot(out.Mars.Time/1e6,out.Mars.Eccentricity,'k-',label='DistOrb',zorder=100)
plt.plot(t/1e6,e,'0.5',label='HNBody')
plt.xlim(0,1)
plt.ylabel('$e$')
plt.xlabel('Time (Myr)')
plt.text(0.05,0.05,'Mars',transform=ax.transAxes)

plt.subplot(4,2,8)
plt.plot(out.Mars.Time/1e6,out.Mars.Inc,'k-',label='DistOrb',zorder=100)
plt.plot(t/1e6,inc,'0.5',label='HNBody')
plt.xlim(0,1)
plt.ylabel('$i$ ($^{\circ}$)')
plt.xlabel('Time (Myr)')

plt.savefig('InnerSolOrbs.pdf')
plt.close()

######################################################################
fig = plt.figure(figsize=(8.5,8))
fig.subplots_adjust(hspace=0.1,wspace=0.23)

t, a, e, inc, longa, argp, ma = np.loadtxt('hnbdata/5.dat',unpack=True)
ax=plt.subplot(4,2,1)
plt.plot(out.Jupiter.Time/1e6,out.Jupiter.Eccentricity,'k-',label='DistOrb',zorder=100)
plt.plot(t/1e6,e,'0.5',label='HNBody')
plt.xlim(0,1)
plt.ylabel('$e$')
plt.xticks(visible=False)
plt.text(0.05,0.05,'Jupiter',transform=ax.transAxes)

plt.subplot(4,2,2)
plt.plot(out.Jupiter.Time/1e6,out.Jupiter.Inc,'k-',label='DistOrb',zorder=100)
plt.plot(t/1e6,inc,'0.5',label='HNBody')
plt.xlim(0,1)
plt.ylabel('$i$ ($^{\circ}$)')
plt.xticks(visible=False)
plt.legend(loc='upper right',fontsize=10,ncol=2)

t, a, e, inc, longa, argp, ma = np.loadtxt('hnbdata/6.dat',unpack=True)
ax=plt.subplot(4,2,3)
plt.plot(out.Saturn.Time/1e6,out.Saturn.Eccentricity,'k-',label='DistOrb',zorder=100)
plt.plot(t/1e6,e,'0.5',label='HNBody')
plt.xlim(0,1)
plt.ylabel('$e$')
plt.xticks(visible=False)
plt.text(0.05,0.9,'Saturn',transform=ax.transAxes)

plt.subplot(4,2,4)
plt.plot(out.Saturn.Time/1e6,out.Saturn.Inc,'k-',label='DistOrb',zorder=100)
plt.plot(t/1e6,inc,'0.5',label='HNBody')
plt.xlim(0,1)
plt.ylabel('$i$ ($^{\circ}$)')
plt.xticks(visible=False)

t, a, e, inc, longa, argp, ma = np.loadtxt('hnbdata/7.dat',unpack=True)
ax=plt.subplot(4,2,5)
plt.plot(out.George.Time/1e6,out.George.Eccentricity,'k-',label='DistOrb',zorder=100)
plt.plot(t/1e6,e,'0.5',label='HNBody')
plt.xlim(0,1)
plt.ylabel('$e$')
plt.xticks(visible=False)
plt.text(0.05,0.85,'Uranus',transform=ax.transAxes)

plt.subplot(4,2,6)
plt.plot(out.George.Time/1e6,out.George.Inc,'k-',label='DistOrb',zorder=100)
plt.plot(t/1e6,inc,'0.5',label='HNBody')
plt.xlim(0,1)
plt.ylabel('$i$ ($^{\circ}$)')
plt.xticks(visible=False)

t, a, e, inc, longa, argp, ma = np.loadtxt('hnbdata/8.dat',unpack=True)
ax=plt.subplot(4,2,7)
plt.plot(out.Neptune.Time/1e6,out.Neptune.Eccentricity,'k-',label='DistOrb',zorder=100)
plt.plot(t/1e6,e,'0.5',label='HNBody')
plt.xlim(0,1)
plt.ylabel('$e$')
plt.xlabel('Time (Myr)')
plt.text(0.05,0.85,'Neptune',transform=ax.transAxes)

plt.subplot(4,2,8)
plt.plot(out.Neptune.Time/1e6,out.Neptune.Inc,'k-',label='DistOrb',zorder=100)
plt.plot(t/1e6,inc,'0.5',label='HNBody')
plt.xlim(0,1)
plt.ylabel('$i$ ($^{\circ}$)')
plt.xlabel('Time (Myr)')

plt.savefig('OuterSolOrbs.pdf')
plt.close()
