name: tests-macos
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    name: '${{ matrix.os }}:python-${{ matrix.python-version }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        if: steps.setup_python.outcome == 'success'
        run: |
          python -m pip install -U pip
          python -m pip install -e .
          python -m pip install pytest pytest-cov

      - name: Run tests
        if: steps.setup_python.outcome == 'success'
        run: make test

      - name: Check test ouptut created
        id: check_test_file
        uses: andstor/file-existence-action@v2
        with:
          files: "/home/runner/work/vplanet/vplanet/junit/test-results.xml"
          fail: true

      - name: Get unique id
        uses: Tiryoh/gha-jobid-action@v1
        id: jobs

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: junit/test-*.xml
